### ISSUE TITLE
Performance decrease after migration to new lib version

### ISSUE THREAD

**Issue by gitazem** [googleads/googleads-php-lib#243] opened 2017-02-17 09:13 UTC
Hello, 

I migrated from v13 to v25. I am downloading many reports (very big amount of accounts and data). I have tested with one account and time increased 2x. 

This is from PHP side because I can't cache objects, lib creating objects on each account. When downloading many accounts each optional action is very sensitive in performance. 

1) On each account i have build session because i want to change client customer  Id. In old version i can create user (master user) cache that variable and in process only set customer id. 

2) I can't cache ReportDownloader class, because each time i have create new class one with newly builded session with changed client customer id. 

Performance is very important thing.. 

1) 
```php        
$oAuth2Credential = (new OAuth2TokenBuilder())->fromFile()->build();
$sessionBuilder = (new AdWordsSessionBuilder())->fromFile()>withOAuth2Credential($oAuth2Credential);
$reportSettings = (new ReportSettingsBuilder())->fromFile()->build();
$sessionBuilder->withReportSettings($reportSettings);

foreach ($accounts as $account) {
       $session = $sessionBuilder->withClientCustomerId($account->getAccountId())->build();
       $this->downloader->getReport($session, $query, $parameters);
}
```

2) 
```php  
 $reportDownloadResult = (new ReportDownloader($session))->downloadReportWithAwql(
            (new QueryFactory())->createDefinition($query),
            $query->getReportFormat()
);

$reportDownloadResult->saveToFile($query->getFilePath());
```

**Comment by fiboknacky** [comment] 2017-02-17 15:22
Hello @gitazem 

Could you please add more details like supporting evidence that being not able to reuse AdWordsSession deteriorate the performance in your case?
We're willing to make a change, of course, but I'd like to ensure that the cause is really fixed.

Thank you so much in advance.

Best,
Knack

**Comment by gitazem** [comment] 2017-02-20 13:12
Hello, thanks for your reply. 

I just done two checks:

19 accounts vs ~10mln rows, 3 different reports.  
1) old version took 434 ms (~7 mins)
3) new version took 727 ms  (~12 mins)

same reports i downloading for ~200 accounts. With old version it took ~1h 32 mins and now in new version it take almost 3 hours.

I am not saying that problem is totally there, its just what i see different and because i am working on performance a lot i am trying to not create new objects on each iteration. 
 
Whats' the best practice in working with a such amount data ?

**Comment by gitazem** [comment] 2017-02-20 14:20
I profiled little bit more and noticed that "save to file" takes ~76% of all processing time. its very strange that full processing time increased. I am not sure why yet. 

![screen shot 2017-02-20 at 16 09 04](https://cloud.githubusercontent.com/assets/7699220/23128623/4225784e-f788-11e6-90e2-a1efb512af18.png)

**Comment by fiboknacky** [comment] 2017-02-21 05:48
Hello @gitazem 

Thanks so much for your additional information.
I just wonder if you could figure out that the increase in time resulted from the downloading process (which is affected directly by `ReportDownloader` and `AdWordsSessionBuilder`) or by the writing of result to files.

From the data at hand, it's tempting to think that the writing of result to files is likely a cause, not because of whether we can change `clientCustomerId` in `AdWordsSession` directly or not?

Best,
Knack

**Comment by gitazem** [comment] 2017-02-21 07:16
Hello @fiboknacky,

New object building many times takes little bit longer. if i cache object it take 0.231ms and if not it take 0.394 ms. 

But as I wanted to say in my last comment - bottle neck is not there, i was wrong, there is too small time increase comparing with full download. You don't need to change it. 

I am not sure where is a problem that download time increased so much. There is bigger problem.. 

Best,
Gita

**Comment by fiboknacky** [comment] 2017-02-22 04:54
Hello @gitazem 

Thanks for confirming.
I close this bug for now as it's obvious from your result that the performance issue isn't caused by the current codes.
Feel free to reach out to us again if you find other interesting information.

Cheers,
Knack

**Closed by fiboknacky** 2017-02-22 04:54 UTC

**Comment by gitazem** [comment] 2017-02-22 07:41
Thank you, for your time. If I'll find where is a problem i will reach you.
