### ISSUE TITLE
reporing messy code

### ISSUE THREAD

**Issue by shanglei001** [googleads/googleads-php-lib#442] opened 2018-01-22 08:57 UTC
Hi,
The text character messy code when download by reporting. Is there anyway to make it display normal ?
![qq 20180122165634](https://user-images.githubusercontent.com/34848634/35212509-5e048fc6-ff95-11e7-9761-423e0150972f.png)

**Comment by fiboknacky** [comment] 2018-01-22 09:08
Hello,

Could you clarify what part is "messy" by your definition?
I think the campaign name is in Chinese character, which works as intended?

Best,
Knack

**Comment by shanglei001** [comment] 2018-01-22 09:30
Hi fiboknacky
Downloading data report display messy code because of campaign name in Chinese character. Could API avoid the problem?

**Comment by fiboknacky** [comment] 2018-01-22 09:55
Hi,

I don't get your question. Do you mean you don't want your campaign name in Chinese characters?
From what you captured, it looks like everything is fine.

Best,
Knack

**Comment by shanglei001** [comment] 2018-01-23 03:31
Hi Knack,
Thanks for your reply.
We need the campaign name in Chinese character. But the result of Chinese character displayed "unrecognized character". What should we do to make Chinese character normal and not display "unrecognized character".

**Comment by fiboknacky** [comment] 2018-01-23 05:36
Hello @shanglei001 

Could you please tell me the following?
*  Your campaign ID whose name is shown with unrecognized character.
*  What is the unrecognized character.
*  Your report definition or AWQL query.

Best,
Knack

**Comment by shanglei001** [comment] 2018-01-23 09:48
Hi Knack,

![qq 20180123144907](https://user-images.githubusercontent.com/34848634/35261742-9be06164-004c-11e8-9ebc-7cf6e559177d.png)

Please see the attached picture. “GNSS-1 鍖楃編”  is not the standard Chinese encoding. We thought it did not turn into utf-8 encoding format when derived data. "Unrecognized character" in Excel cell B9 in the picture result in "enabled" data displaying in C9. The data in the following cell all displayed in its front cell result in data can not correspond.

My code as follows：
`
$selector = new Selector();
$selector->setFields(['CampaignId', 'CampaignName', 'CampaignStatus', 'Amount',  'Clicks', 'Cost', 'CostPerConversion', 'Ctr', 'ConversionRate']);
$reportDefinition = new ReportDefinition();
$reportDefinition->setSelector($selector);
$reportDefinition->setReportName('Criteria performance report #' . uniqid());
$reportDefinition->setDateRangeType(ReportDefinitionDateRangeType::YESTERDAY);
$reportDefinition->setReportType(ReportDefinitionReportType::CAMPAIGN_PERFORMANCE_REPORT);
$reportDefinition->setDownloadFormat(DownloadFormat::CSV);
`
Thinks

**Comment by fiboknacky** [comment] 2018-01-23 10:19
Hello Shanglei,

Could you please tell me the **exact** campaign IDs of cell B3 and B9 please? 
You attached screenshot didn't show them. :)

Best,
Knack

**Comment by shanglei001** [comment] 2018-01-25 02:21
Hi Knack,

Thanks for your reply. Downloading data displayed "unrecognized character". We are trying to read data. The output data display normal.

![qq 20180125101153](https://user-images.githubusercontent.com/34848634/35367496-89713242-01b9-11e8-9c44-29397ac6014f.png)


Thanks again for your help.

**Comment by fiboknacky** [comment] 2018-01-25 05:38
Looks like you could resolve the issue so I'll close this.

**Closed by fiboknacky** 2018-01-25 05:38 UTC
Labels: P2
