### ISSUE TITLE
 $reportDefinition->selector->dateRange->min  throwing "PHP message: PHP Warning:  Creating default object from empty value 

### ISSUE THREAD

**Issue by lesterjanpearson** [googleads/googleads-php-lib#92] opened 2015-07-14 19:34 UTC
Its throwing the 

"PHP message: PHP Warning:  Creating default object from empty value 

on this part of the code.

$reportDefinition->dateRangeType = 'CUSTOM_DATE';
$reportDefinition->selector->dateRange->min = $date_from;
$reportDefinition->selector->dateRange->max = $date_to;

**Comment by vtsao** [comment] 2015-07-15 00:48
Thanet can you please take a look at this? Thanks.

**Comment by fiboknacky** [comment] 2015-07-15 02:27
Will have a look at this.

**Comment by lesterjanpearson** [comment] 2015-07-16 23:37
adding 
$reportDefinition->selector->dateRange = new stdClass;
before
$reportDefinition->selector->dateRange->min = $date_from;

fix this

**Comment by fiboknacky** [comment] 2015-07-17 06:24
What part of code are your referring to?
`$reportDefinition->dateRangeType = 'CUSTOM_DATE';` appears in [DownloadCriteriaReport.php](https://github.com/googleads/googleads-php-lib/blob/bb6e7f99905091fd5081f1557b981c0e060b4e9d/examples/AdWords/v201506/Reporting/DownloadCriteriaReport.php), but I couldn't find the `selector->dateRange->min` you mentioned.

**Comment by lesterjanpearson** [comment] 2015-07-21 05:34
if you use 
$reportDefinition->dateRangeType = 'CUSTOM_DATE';

You would need to specify min and max dates, but for php config with E_STRICT on,
it will throw error message
"PHP message: PHP Warning: Creating default object from empty value
there for by adding this:

$reportDefinition->selector->dateRange = new stdClass;

before

$reportDefinition->selector->dateRange->min = $date_from;
$reportDefinition->selector->dateRange->max = $date_to;

will fix the issue.

Final code on 
$reportDefinition->dateRangeType = 'CUSTOM_DATE';
$reportDefinition->selector->dateRange = new stdClass;
$reportDefinition->selector->dateRange->min = $date_from;
$reportDefinition->selector->dateRange->max = $date_to;

**Comment by vtsao** [comment] 2015-07-21 16:59
Are you referencing one of our examples? Which of our examples has this bug?

**Comment by hakimio** [comment] 2015-08-05 11:14
@lesterjanpearson
There is nothing wrong with the library or their examples. The problem is that you don't understand how to use it.
Here is how you are supposed to set custom date:
```php
$selector = new Selector();
$selector->dateRange = new DateRange($startDate, $endDate);
$reportDefinition = new ReportDefinition();
$reportDefinition->selector = $selector;
$reportDefinition->dateRangeType = 'CUSTOM_DATE';
```

**Comment by fiboknacky** [comment] 2015-08-06 04:26
It seems irrelevant to our code example here, so I'll close this issue.
Thanks @hakimio for giving more example too.

**Closed by fiboknacky** 2015-08-06 04:26 UTC
Labels: bug
