### ISSUE TITLE
TargetingIdeaSelector::setRequestedAttributeTypes() accepts array, not string

### ISSUE THREAD

**Issue by BenMorel** [googleads/googleads-php-lib#296] opened 2017-05-21 14:44 UTC
According to the [documentation](https://developers.google.com/adwords/api/docs/reference/v201702/TargetingIdeaService.TargetingIdeaSelector#requestedattributetypes), `TargetingIdeaSelector::setRequestedAttributeTypes()` accepts an array of `AttributeType` values.

However, the PHP SDK weirdly [expects a string](https://github.com/googleads/googleads-php-lib/blob/26.0.0/src/Google/AdsApi/AdWords/v201702/o/TargetingIdeaSelector.php#L129-L137):

    /**
     * @param string $requestedAttributeTypes
     * @return \Google\AdsApi\AdWords\v201702\o\TargetingIdeaSelector
     */
    public function setRequestedAttributeTypes($requestedAttributeTypes)
    {
      $this->requestedAttributeTypes = $requestedAttributeTypes;
      return $this;
    }

But it indeed works with an array (just tested it):

    $selector->setRequestedAttributeTypes([
        AttributeType::KEYWORD_TEXT,
        AttributeType::COMPETITION,
        AttributeType::SEARCH_VOLUME,
        AttributeType::AVERAGE_CPC,
        AttributeType::TARGETED_MONTHLY_SEARCHES
    ]);

**Comment by fiboknacky** [comment] 2017-05-22 02:34
Hi @BenMorel,

Thanks for reporting.
Will have a look at this.

Best,
Knack

**Comment by fiboknacky** [comment] 2017-06-01 07:08
This is a duplicate of #292. Please follow up in that issue instead.
Thanks for reporting again.

Knack

**Closed by fiboknacky** 2017-06-01 07:08 UTC
Labels: duplicate
