### ISSUE TITLE
Unable to install due to guzzlehttp/psr7 version conflict

### ISSUE THREAD

**Issue by nhtahoe** [googleads/googleads-php-lib#210] opened 2017-01-06 19:20 UTC
Unable to install this library due to a version conflict with guzzlehttp/psr7. Here is the output I get when I run the composer install:

> composer require googleads/googleads-php-lib
> Using version ^25.0 for googleads/googleads-php-lib
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - googleads/googleads-php-lib 25.0.0 requires google/auth ^0.7 -> satisfiable by google/auth[v0.7].
>     - Installation request for googleads/googleads-php-lib ^25.0 -> satisfiable by googleads/googleads-php-lib[25.0.0].
>     - Conclusion: remove guzzlehttp/psr7 1.3.1
>     - Conclusion: don't install guzzlehttp/psr7 1.3.1
>     - google/auth v0.7 requires guzzlehttp/psr7 1.2.* -> satisfiable by guzzlehttp/psr7[1.2.0, 1.2.1, 1.2.2, 1.2.3].
>     - Can only install one of: guzzlehttp/psr7[1.2.0, 1.3.1].
>     - Can only install one of: guzzlehttp/psr7[1.2.1, 1.3.1].
>     - Can only install one of: guzzlehttp/psr7[1.2.2, 1.3.1].
>     - Can only install one of: guzzlehttp/psr7[1.2.3, 1.3.1].
>     - Installation request for guzzlehttp/psr7 (locked at 1.3.1) -> satisfiable by guzzlehttp/psr7[1.3.1].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by petrjirasek** [comment] 2017-01-07 12:36
I have the same problem, any solution please?

**Comment by nhtahoe** [comment] 2017-01-07 19:04
I was able to get the ads API PHP client library v 25 install to work by
first adding the following line in the "require" section of my
composer.json file as an inline alias:
"guzzlehttp/psr7": "1.2.3 as 1.3.1"
I'm not sure if this will break other things, but it did let me at least
install the library.

**Comment by petrjirasek** [comment] 2017-01-09 18:30
In my case Amazon SDK requires 1.3.1 so I am not sure if it is a good idea:)
On 07.01.2017 20:05:06, nhtahoe <notifications@github.com> wrote:
I was able to get the ads API PHP client library v 25 install to work by
first adding the following line in the "require" section of my
composer.json file as an inline alias:
"guzzlehttp/psr7": "1.2.3 as 1.3.1"
I'm not sure if this will break other things, but it did let me at least
install the library.

**Comment by vtsao** [comment] 2017-01-09 19:41
Thanks everybody for reporting this. The issue is that the min required version of google-auth currently in this library's Composer file is 0.7. In that version, google-auth defined the Guzzle PSR-7 dep as "1.2.*", which is more limiting than it needs to be (since Guzzle follows semantic versioning) and causes the unsatisfiable package deps (since most people are using a later version of Guzzle PSR7 it seems).

But now google-auth has corrected this and now defines this dep as "~1.2", which is a better practice.

I'll update this library to use the latest release of google-auth (0.10), which should resolve this issue.

**Comment by vtsao** [comment] 2017-01-09 21:55
Actually it should be google-auth ^0.11.0.

**Comment by vtsao** [comment] 2017-01-11 17:38
This issue is fixed in [release v25.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.1.0).

**Closed by vtsao** 2017-01-11 17:38 UTC
Labels: bug
