### ISSUE TITLE
Incorrect usage of phpdoc

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#90] opened 2015-07-02 11:29 UTC
In most places of this library phpdoc is used incorrectly. For example, right now mutate method definition in AdGroupAdService looks like this:
```php
     /* 
     * @param operations The operations to apply.
     * @return A list of AdGroupAds where <...>
     */
    public function mutate($operations)
```

Where the correct way to define this would be the following way:
```php
     /* 
     * @param AdGroupAdOperation[] $operations The operations to apply.
     * @return AdGroupAdReturnValue A list of AdGroupAds where <..>
     */
    public function mutate($operations)
```

Same for the get method. Current usage:
```php
     /* 
     * @param serviceSelector The selector specifying the {@link AdGroupAd}s to return.
     * @return The page containing the AdGroupAds that meet the criteria specified  <..>
     * @throws ApiException when there is at least one error with the request.
     */
    public function get($serviceSelector) 
```
Correct way to define it:
```php
     /* 
     * @param Selector $serviceSelector The selector specifying the <...>
     * @return AdGroupAdPage The page containing the AdGroupAds that meet the <..>
     * @throws ApiException when there is at least one error with the request.
     */
    public function get($serviceSelector) 
```

The biggest problem with incorrect phpdoc usage is that it confuses static code analysis present in most advanced IDEs and it shows loads of warnings just from your library.
More information about correct phpdoc usage can be found [here](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/param.html).
Most of the problems could be fixed with a simple regex search & replace, while some of them would require manual editing. I could fix the latest version of Adwords API if you don't have the time or don't think it's worth your time and then either send a patch or push request if you are willing to accept it.

**Comment by vtsao** [comment] 2015-07-02 21:21
Yeah, these files are currently generated from the WSDLs with an outdated tool. We're working on replacing this tool in the near future, which will hopefully fix this issue.

Closing this as a duplicate of:
https://github.com/googleads/googleads-php-lib/pull/86

**Closed by vtsao** 2015-07-02 21:21 UTC

**Comment by hakimio** [comment] 2015-07-02 21:44
Hopefully near future is within few weeks because this bug is pretty annoying.
