### ISSUE TITLE
Composer installation error

### ISSUE THREAD

**Issue by Shuyinsama** [googleads/googleads-php-lib#213] opened 2017-01-10 11:18 UTC
Hello,

I saw the thread for the Guzzle error and some older errors but somehow all the solutions don't work.
I wasn't sure if I needed to start a new issue but I didn't really want to hijack the other issue.

Anyway I am trying to require this library inside a Laravel project.

In this project I also connect to the `google/apiclient` package so I can get data from Analytics.
Now I want to connect to DFP but I am getting a conflict in terms of `minimum-stability`

Here is the error I get when I do
```shell
composer require googleads/googleads-php-lib
```

```shell
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for googleads/googleads-php-lib ^25.0 -> satisfiable by googleads/googleads-php-lib[25.0.0].
- googleads/googleads-php-lib 25.0.0 requires google/auth ^0.7 -> satisfiable by google/auth[v0.7] but these conflict with your requirements or minimum-stability.
```

Does this mean the `googleads-php-lib``` needs the 0.7 version of `google/auth`?
Cause I am requiring version 0.11.1

Here is my `composer.json`

```javascript
{
    "name": "rappasoft/laravel-5-boilerplate",
    "description": "The Laravel Framework Boilerplate Project.",
    "keywords": ["framework", "laravel", "boilerplate"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "5.3.*",
        "laravel/socialite": "^2.0",
        "creativeorange/gravatar": "~1.0",
        "davejamesmiller/laravel-breadcrumbs": "^3.0",
        "hieu-le/active": "~2.0",
        "arcanedev/log-viewer": "~4.0",
        "arcanedev/no-captcha": "~3.0",
        "yajra/laravel-datatables-oracle": "~6.0",
        "google/auth": "^0.11.1",
        "google/apiclient": "^2.1",
        "facebook/graph-sdk" : "~5.0",
        "abraham/twitteroauth": "^0.6.6",
        "guzzlehttp/guzzle": "^6.2",
        "jenssegers/mongodb": "^3.1",
        "googleads/googleads-php-lib": "^25.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "barryvdh/laravel-debugbar": "^2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

```

**Comment by vtsao** [comment] 2017-01-11 17:35
Hi @Shuyinsama, thanks for reporting this. This is a duplicate of issue #200.

**Closed by vtsao** 2017-01-11 17:35 UTC
