### ISSUE TITLE
Composer Require Issues

### ISSUE THREAD

**Issue by StephenRostantiBoonsMedia** [googleads/googleads-php-lib#767] opened 2022-11-30 15:27 UTC
When I run:
$ composer require googleads/googleads-php-lib

I get:

Problem 1
    - Root composer.json requires googleads/googleads-php-lib ^59.0 -> satisfiable by googleads/googleads-php-lib[59.0.0].
    - googleads/googleads-php-lib 59.0.0 requires symfony/serializer ^3.0.3 || ^4.4.0 || ^5.0.0 -> found symfony/serializer[v3.0.3, ..., v3.4.47, v4.4.0, ..., v4.4.47, v5.0.0, ..., v5.4.15] but it conflicts with your root composer.json require (6.1.*).

**Comment by PierrickVoulet** [comment] 2022-12-16 16:39
Hi @StephenRostantiBoonsMedia - Looks like you require the version `6.1` for `symfony/serializer` but we currently only support up to version `5`.  You may want to downgrade your requirement to allow the version `5` to be compatible.

**Comment by PierrickVoulet** [comment] 2023-01-20 15:25
Closing this issue because it is a duplicate of #739

**Closed by PierrickVoulet** 2023-01-20 15:25 UTC
Labels: enhancement
