### ISSUE TITLE
Adwords API giving issue

### ISSUE THREAD

**Issue by chiragvels** [googleads/googleads-php-lib#659] opened 2020-04-23 05:51 UTC
Hi,
Adwords API is giving issue and not preparing soap suddenly giving me Memory error.
Till Yesterday it was working fine.

Can you please check?

Thanks,

**Comment by fiboknacky** [comment] 2020-04-23 05:58
> Adwords API is giving issue and not preparing soap suddenly giving me Memory error.

Could you give more detail please?
If it looks like the issue of the API server, please post on the [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
It'd be escalated much faster.

Best,
Knack

**Comment by chiragvels** [comment] 2020-04-23 07:05
Hi @fiboknacky ,

More details.

Not able to prepare SOAP

SoapFault Object
(
    [message:protected] => Allowed memory size of 134217728 bytes exhausted (tried to allocate 2141656822 bytes)
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php
    [line:protected] => 83
    [trace:Exception:private] => Array

Thanks,

**Comment by fiboknacky** [comment] 2020-04-23 07:36
We've not changed anything on our side. 
This looks more like an issue of your computing environment.
Have you tried [this](https://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml)?

**Comment by chiragvels** [comment] 2020-04-23 07:42
HI @fiboknacky ,

I am also sure, I have not changed any settings.
Let me check that link also.

Thanks,

**Comment by chiragvels** [comment] 2020-04-23 09:05
HI @fiboknacky ,

I have checked the same and found that there seems to be an issue with Response from the server.
I am able to prepared adwords session but not able to get campaigns list with get.

```
$oAuth2Credential = (new OAuth2TokenBuilder())
                    ->fromFile(ADS_INI_PATH)
                    ->withRefreshToken($refresh_token)                                      
                    ->build();          

            $session = (new AdWordsSessionBuilder())
                    ->fromFile(ADS_INI_PATH)
                    ->withOAuth2Credential($oAuth2Credential)  
                    ->withClientCustomerId($client_id)
                    ->build();

            print_r($session);

            $campaignService = (new AdWordsServices)->get($session, CampaignService::class);
            
            $selector = new Selector();
            $selector->setFields(['Id', 'Name', 'Status']);             
            $page = $campaignService->get($selector);
            print_r($page);
```
In above code I am not able to get $campaignService .
But able to print $session .

Can you please help?

Thanks,

**Comment by fiboknacky** [comment] 2020-04-23 10:40
Unfortunately, I cannot reproduce this issue. It runs very well in my machine.
Would you be able to change your environments / machines and try?

**Comment by chiragvels** [comment] 2020-04-23 12:22
Okay,

Let me ask Server guys.

Any suggestion to check in a specific API response?

I was getting CustomerService and ManageCustomerService get the operation done, but only issue with few of the get operation.

Thanks,

**Comment by fiboknacky** [comment] 2020-04-23 12:38
I don't get your question. Could you please paraphrase it?
Do you mean you can use CustomerService and ManagedCustomerService, but cannot get the result from what services?

By the way, for AdWords API-related general questions, please consider asking in this [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) as well. :-)

**Comment by chiragvels** [comment] 2020-04-23 14:06
> I don't get your question. Could you please paraphrase it?
> Do you mean you can use CustomerService and ManagedCustomerService, but cannot get the result from what services?


Yes, But not CampaignService, Adgroup Service etc..
 

> By the way, for AdWords API-related general questions, please consider asking in this AdWords API forum as well. :-)



Ok, I have asked there.

https://groups.google.com/d/topic/adwords-api/tFJabPaEoWg/discussion


Thanks,

**Comment by fiboknacky** [comment] 2020-09-29 02:05
Closing this issue, as it's discussed on our forum now.

**Closed by fiboknacky** 2020-09-29 02:05 UTC
