### ISSUE TITLE
I am getting error when Run Saved Query on console

### ISSUE THREAD

**Issue by akashsky44** [googleads/googleads-php-lib#450] opened 2018-02-22 11:49 UTC
PHP Fatal error:  Uncaught Error: Call to a member function getIsCompatibleWithApiVersion() on null in /var/www/www.example.com/public_html/dfp/examples/Dfp/v201802/ReportService/RunSavedQuery.php:60
Stack trace:
#0 /var/www/www.example.com/public_html/dfp/examples/Dfp/v201802/ReportService/RunSavedQuery.php(100): Google\AdsApi\Examples\Dfp\v201802\ReportService\RunSavedQuery::runExample(Object(Google\AdsApi\Dfp\DfpServices), Object(Google\AdsApi\Dfp\DfpSession), 10019354480)
#1 /var/www/www.example.com/public_html/dfp/examples/Dfp/v201802/ReportService/RunSavedQuery.php(104): Google\AdsApi\Examples\Dfp\v201802\ReportService\RunSavedQuery::main()
#2 {main}
  thrown in /var/www/www.example.com/public_html/dfp/examples/Dfp/v201802/ReportService/RunSavedQuery.php on line 60

Compatible Api Version errror getting besides this everything working fine but when used inside Report Service Saved Query I am getting error in v201802, v201711, etc..

**Comment by fiboknacky** [comment] 2018-02-22 11:58
Thang, could you please take a look?

**Comment by thangduo** [comment] 2018-02-22 15:22
Sure, I'll take a look today.

Thanks,
Thang Duong


Thang Duong | Developer Advocate | dcthang@google.com | 650-793-5832

**Comment by akashsky44** [comment] 2018-02-23 07:09
Hello Thang, 
I am getting the error with attached in this. when running this saved query on a console where I put query ID in RunSavedQuery.php file. 

![screenshot from 2018-02-23 12-28-32](https://user-images.githubusercontent.com/17689498/36582034-cd6ec1d8-1895-11e8-9e3c-88f316081716.png)

Please solve this. and also I want to execute that file in a browser. How to do that Please give me any idea.

Thanks

**Comment by thangduo** [comment] 2018-02-23 16:26
The error "Call to a member function getIsCompatibleWithApiVersion() on null" indicates that there is no saved queries returned by the previous function:
```
$savedQuery = $savedQueryPage->getResults()[0]; // $savedQuery is null and will cause 
                                                // exceptions on subsequent lines
```
Saved queries are private to the creator user.

If you are using a service account to access a saved query created by a non-service account user, please make sure the saved query is shared with the service account.

![Users able to edit](https://user-images.githubusercontent.com/4349155/36604174-f06c81b2-188a-11e8-8c01-8dae25f8118c.png)

This article has a step by step instruction:
https://support.google.com/dfp_premium/answer/6098531?hl=en&ref_topic=7492017

Please let me know if sharing the saved query would fix your issue.

Thanks,
Thang Duong


Closing remark: I am closing this issue and mark it as Invalid because this is not a bug.

**Comment by akashsky44** [comment] 2018-02-26 06:42
Hello Thang,

I already have done that but I am getting the same error on my console screen. It's not fixed my sharing saved query issue. Pleas suggest

**Comment by thangduo** [comment] 2018-02-26 16:26
Sorry to hear that you still get the error.

Could you please share your network id and the shared query id?

Thanks,
Thang Duong

**Comment by akashsky44** [comment] 2018-02-27 07:07
Network id is 2676262
Shared Query id is 10019354480

**Comment by thangduo** [comment] 2018-02-28 16:35
Which user account is the owner of the saved query?

**Comment by thangduo** [comment] 2018-03-01 15:00
Please update this thread if this issue is still blocking you.

**Comment by akashsky44** [comment] 2018-03-01 16:25
Another account is owner of saved query. And i am still facing issue.

**Comment by thangduo** [comment] 2018-03-02 15:16
I will need to know the name of the account who owns the query in order to reproduce the issue on my end.

Please update this thread with the owner account's name.

**Comment by akashsky44** [comment] 2018-03-02 16:26
Account owner : mindworksceo@gmail.com

**Comment by thangduo** [comment] 2018-03-12 13:19
Hi Akash,

The report that you are trying to generate has some dimensions that are not compatible with the API. Please try to adjust the dimensions and retry.

Thanks

**Comment by thangduo** [comment] 2018-03-28 13:56
Hi Akash,

I am closing this issue due to inactivity.

For reference:
- If the saved query is not shared with the OAuth account that makes the SOAP request, the `getSavedQueriesByStatement()` function will not return the saved query.

- If a query is not compatible with your API version, `SavedQuery.reportQuery` will be `null` and `SavedQuery.isCompatibleWithApiVersion` will be `false`. Please refer to our [Reporting Basics guide](https://developers.google.com/doubleclick-publishers/docs/reporting).

- A saved query will be incompatible with the API if it uses columns, dimensions, or other
reporting features from the UI that are not available in the [`ReportQuery` entity](https://developers.google.com/doubleclick-publishers/docs/reference/v201802/ReportService.ReportQuery).

**Comment by MountainMaster** [comment] 2019-02-22 09:15
Hi @thangduo 

I do have the same problem.

Reports are shared with the service account I am using, but "getSavedQueriesByStatement" gives me results=NULL.

Can you help me with that problem?
network id 183
report id e.g. 11137633886

kind regards
Tobias

**Comment by thangduo** [comment] 2019-02-25 20:51
Hi Tobias,

What is the saved query ID? what is the email address that owns the saved query?
Are you able to run the saved query via the UI?

Thanks,
Thang Duong

**Comment by MountainMaster** [comment] 2019-03-06 13:55
Hi Thang,

I found the problem.
I was given report IDs instead of query IDs.

Thanks

**Closed** 2019-03-14 17:47 UTC
Labels: P2

**Comment by khoadd101** [comment] 2020-02-14 04:24
Hi Thang,

I'm using API v201911, i have the same error.
If i delete filter option: DFP Ad Units (Top Level) from the saved query and run, i received a good result.
Please let's me know what wrong?
Thanks for your support!

**Comment by thangduo** [comment] 2020-02-14 14:57
Hi khoadd101,

Please specify your network id, query id and name of the account who owns the query.

Thanks,
Thang Duong

**Comment by khoadd101** [comment] 2020-02-17 01:53
Hi Thang,

Thanks for your support!

Query id=11549385028, network code=93656639
DFP Ad Units (Top Level) dimension/filter is not yet supported in the Ad Manager API v201911?
Please check and let me know.

Thanks,
Khoadd101

**Comment by IK-github** [comment] 2020-08-17 17:59
Hi Thang,
I'm using API v202005, i have the same error for RunSavedQuery.php example.
**Fatal error: Uncaught UnexpectedValueException: The saved query is not compatible with this API version.**

name = my-report,
report_id=11774255125 ,
network code= 7047

**************************
it's not working for me
**************************
        // Create statement to retrieve the saved query.
        $statementBuilder = (new StatementBuilder())->where('id = :id')
            ->orderBy('id ASC')
            ->limit(1)
            ->withBindVariableValue('id', $savedQueryId);

        $savedQueryPage = $reportService->getSavedQueriesByStatement(
            $statementBuilder->toStatement()
        );
        $savedQuery = $savedQueryPage->getResults()[0];

        if ($savedQuery->getIsCompatibleWithApiVersion() === false) {
            throw new UnexpectedValueException(
                'The saved query is not compatible with this API version.'
            );
        }

        // Optionally modify the query.
        $reportQuery = $savedQuery->getReportQuery();
**************************

Can you help me with that problem? 
How should I create a statement to retrieve the saved query?
Please, let me know what i'm doing wrong.

Thank you for support!
