### ISSUE TITLE
Unable to use wsdl files

### ISSUE THREAD

**Issue by AntoineTB** [googleads/googleads-php-lib#410] opened 2017-12-05 04:58 UTC
> Dev Machine on Windows 10
> Apache/2.4.18 (Win32) OpenSSL/1.0.2f PHP/7.0.3
> API Version 32.0 freshly installed via Composer

Hi.
Our application has gradually stopped being able to parse wsdls from the api in the last few days. Some changes to our server config have been made trying to resolve the issue, and mostly we migrated to 32.0 in hope of using the local wsdl files included in `resources`, but this didn't prove to be succesfull. I am also unclear about how this kind of problem can be gradual : Another dev machine could parse the WSDLs about once out of 20 times, then couldn't at all.

Trying to instanciate a service, by calling an [example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201705/BasicOperations/GetCampaigns.php), gives this result : 

> $ php test_connectivity.php
> Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl
> '  failed to load external entity "https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl"  in [...]\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 76

I was suprised to see a call to the adwords wsdl file after migrating so I wondered how the local files were managed. I inspected `AdsSoapClient` and noticed that the file verification at line 76 always fail as `$localWsdlPath` doesn't not include the `.wsdl` extension.

Trying to fix this in `__construct()` or in `getLocalWsdlPath()` led me to another error:

> Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in [...]\vendor\googleads\googleads-p
hp-lib\src\Google\AdsApi\Common\AdsSoapClient.php:88

This one I have no idea how to fix.

Ignoring the problems with the local files, I did those debugging checks trying to solve the parsing issue:

- php_soap.dll is properly loaded
- [wsdl file](https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl) is accessible and looks valid from my browser
- wsdl file is correctly fetched by cURL (called from CLI)
- wsdl file is correctly fetched by cURL (called with PHP extension)

In case it can be of any help to isolate the cause of this problem, here is my `adsapi_php.ini`, with comments removed:

> [ADWORDS]
> developerToken = "cH6***"
> clientCustomerId = "79***"
> userAgent = "PHP_AdWords_Keystone"
> [ADWORDS_REPORTING]
> [OAUTH2]
> clientId = "54***.apps.googleusercontent.com"
> clientSecret = "F5***"
> refreshToken = "1/8***"
> [SOAP]
> [PROXY]
> [LOGGING]
> soapLogFilePath = "C:\\log\\soap.log"
> soapLogLevel = "NOTICE"

The log at `C:\log\soap.log` does have entries for the `SoapFault exception` but none for the parsing error.

Thanks in advance

**Comment by hakimio** [comment] 2017-12-05 07:26
Did you enable wsdl caching?

**Comment by hakimio** [comment] 2017-12-05 08:10
Also, might be worth checking if "openssl.cafile" is set correctly.

**Comment by fiboknacky** [comment] 2017-12-05 14:55
Hi @AntoineTB 

Sorry for your inconvenience. I'll release a fix of the local WSDLs issues soon.
As for your case, if your program keeps failing all the time, it might worth checking your SSL CA file as described in [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues) as well.

Best,
Knack

**Comment by AntoineTB** [comment] 2017-12-05 15:41
Hi,
Thanks both of you for your answers, I properly setup `openssl.cafile` and also propagated the certificate settings to all php_ini version to be 100% sure, and it's working again.
I'd like to keep this open to check in on the local WSDL issue if you don't mind.

Thanks again for the quick responses.

**Comment by Vijaysinh** [comment] 2017-12-05 19:12
I am also getting same issue.. started getting error on my system.

**Comment by hakimio** [comment] 2017-12-05 19:16
@Vijaysinh If you can load the wsdl in your browser, then it's from the client library.

**Comment by Vijaysinh** [comment] 2017-12-05 20:12
@hakimio Yes.. in browser its loading

**Comment by fiboknacky** [comment] 2017-12-05 20:17
Hi @Vijaysinh 

Could you please check [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues) too?

Best,
Knack

**Comment by Vijaysinh** [comment] 2017-12-05 20:40
I have updated vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php
$conf[CURLOPT_SSL_VERIFYPEER] = false;
and ->disableSslVerify() worked for me.. is there any other solution for this?

I am using xampp windows64 bit..php 5.6.25

**Comment by fiboknacky** [comment] 2017-12-05 21:48
As a reply to @AntoineTB, the issue is now fixed with [v32.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/32.1.0).

**Comment by fiboknacky** [comment] 2017-12-13 09:12
Close due to inactivity and the issue is already fixed as mentioned.

**Closed by fiboknacky** 2017-12-13 09:12 UTC
