### ISSUE TITLE
Get connection errors on the Adwords API

### ISSUE THREAD

**Issue by rezetta** [googleads/googleads-php-lib#580] opened 2019-03-25 11:05 UTC
Please help. We randomly get these errors after last update.

Removed clientId and full directory listing.

[2019-03-25 11:57:24] AW_REPORT_DOWNLOADER.WARNING: clientCustomerId=111111111111 unknown (AwApi-PHP, googleads-php-lib/40.0.0, PHP/7.2.16, GuzzleHttp/6.3.3, curl/7.29.0, ReportDownloader/file) "POST /api/adwords/reportdownload/v201809 HTTP/1.1" Status: NULL   
[2019-03-25 11:57:24] AW_REPORT_DOWNLOADER.NOTICE: Request:
POST /api/adwords/reportdownload/v201809 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: adwords.google.com
Authorization: REDACTED
developerToken: REDACTED
clientCustomerId: 1111111111111
User-Agent: unknown (AwApi-PHP, googleads-php-lib/40.0.0, PHP/7.2.16, GuzzleHttp/6.3.3, curl/7.29.0, ReportDownloader/file)
skipReportHeader: false
skipColumnHeader: false
skipReportSummary: false
useRawEnumValues: false
includeZeroImpressions: false

__rdxml=<?xml version="1.0"?>
<reportDefinition><selector><fields>AccountDescriptiveName</fields><fields>Date</fields><fields>CampaignName</fields><fields>AdGroupName</fields><fields>ExternalCustomerId</fields><fields>AdGroupStatus</fields><fields>Clicks</fields><fields>Impressions</fields><fields>Ctr</fields><fields>AverageCpc</fields><fields>AverageCpm</fields><fields>Cost</fields><fields>AveragePosition</fields><fields>AdNetworkType1</fields></selector><reportName>Custom ADGROUP_PERFORMANCE_REPORT</reportName><reportType>ADGROUP_PERFORMANCE_REPORT</reportType><dateRangeType>THIS_MONTH</dateRangeType><downloadFormat>XML</downloadFormat></reportDefinition>

Response:
REDACTED REPORT DATA
--------
Error:
Error creating resource: [message] fopen(): Failed to enable crypto
[file] /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201809): failed to open stream: operation failed
[file] /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
  
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(): Failed to enable crypto
[file] /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201809): failed to open stream: operation failed
[file] /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323 in /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(334): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(51): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(52): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /vendor/guzzlehttp/gu in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52

**Comment by fiboknacky** [comment] 2019-03-25 11:38
How often did you get this error?

**Comment by rezetta** [comment] 2019-03-25 11:41
Everytime we connect, but the random clientids. I tried to filter out the
clientids.

**Comment by fiboknacky** [comment] 2019-03-25 11:45
OK. It'd be helpful if you could scope down some client IDs for me.
Thanks!

**Comment by rezetta** [comment] 2019-03-25 11:47
You can't comment at this time.

Why do I get this message on GitHub ?

**Comment by rezetta** [comment] 2019-03-25 11:49
So you want me to share the clientIDs ? They are random.
It looks like the issue is somekind of timeout.

I tried this at my end, but did not work:

$options = [
                    'stream_context' => [
                        'http' => ['timeout' => 120]
                    ]
                ];
                $requestOptionsFactory = new
RequestOptionsFactory($session, $options);

**Comment by fiboknacky** [comment] 2019-03-25 12:12
Sometimes, the client customer IDs do affect the time-out too.
It usually happens when that customer IDs have so much data that it cannot be transferred during that period.

This can sometimes happen transiently.
Try setting shorter date range would help.

**Comment by rezetta** [comment] 2019-03-25 12:22
It happens when I try to get data from one day.

This never happened before? I have not done any changes to the script. And
the first error came on friday last week.

**Comment by fiboknacky** [comment] 2019-03-25 12:29
It happened in the past, but just incidentally it's never happened to any of your customer accounts. :)
So, unfortunately, the only workaround is to reduce the size of your reports.
I see that you requested reasonable numbers of report fields already, so the only probable way for now would be reducing the date range.

You said that it happens when downloading for one day too.
Could you share the client customer ID and the report definition you used?
(I can redact your client customer ID later).

**Comment by rezetta** [comment] 2019-03-25 12:33
Thank you for the patience and help so far :)

ReportDefinitionDateRangeType::YESTERDAY);
        $reportDefinition->setReportType(
                ReportDefinitionReportType::ADGROUP_PERFORMANCE_REPORT);
        $reportDefinition->setDownloadFormat(DownloadFormat::XML);


Also the clientIDs (the ones I have removed so far):
$customersExcluded = array('7665186907', '4556174973', '9311385709',
'3500280295', '1187534719', '4307957666');

**Comment by fiboknacky** [comment] 2019-03-25 12:38
Can you share the report fields you used too?

**Comment by rezetta** [comment] 2019-03-25 12:43
$selector->setFields(['AccountDescriptiveName', 'Date', 'CampaignName',
'AdGroupName', 'ExternalCustomerId', 'AdGroupStatus', 'Clicks',
'Impressions', 'Ctr', 'AverageCpc', 'AverageCpm', 'Cost',
'AveragePosition', 'AdNetworkType1']);

**Comment by afbora** [comment] 2019-03-25 18:42
@rezetta @fiboknacky In my system, i'm downloading account, campaign, ad group, keyword and ad reports of my customers via cronjob periodically. I also getting this error every day for a certain period of time and it works again doing nothing.

> Response:
> REDACTED REPORT DATA
> --------
> Error:
> Client error: `POST https://adwords.google.com/api/adwords/reportdownload/v201809` resulted in a `400 Bad Request` response
>   
> [2019-03-25 04:55:16] AW_REPORT_DOWNLOADER.WARNING: clientCustomerId=9603186354 unknown (AwApi-PHP, googleads-php-lib/40.0.0, PHP/7.3.3, GuzzleHttp/6.3.3, curl/7.64.0) "POST /api/adwords/reportdownload/v201809 HTTP/1.1" Status: 400   
> [2019-03-25 04:55:16] AW_REPORT_DOWNLOADER.NOTICE: Request:
> POST /api/adwords/reportdownload/v201809 HTTP/1.1
> Content-Type: application/x-www-form-urlencoded
> Host: adwords.google.com
> Authorization: REDACTED
> developerToken: REDACTED
> clientCustomerId: 9603186354
> User-Agent: unknown (AwApi-PHP, googleads-php-lib/40.0.0, PHP/7.3.3, GuzzleHttp/6.3.3, curl/7.64.0)
> skipReportHeader: false
> skipColumnHeader: false
> skipReportSummary: false
> useRawEnumValues: false
> includeZeroImpressions: true
> 
> __rdxml=<?xml version="1.0"?>
> <reportDefinition><selector><fields>ExternalCustomerId</fields><fields>Date</fields><fields>Clicks</fields><fields>Impressions</fields><fields>Ctr</fields><fields>AverageCpc</fields><fields>AverageCpm</fields><fields>Cost</fields><fields>AverageCost</fields><fields>AveragePosition</fields><fields>Conversions</fields><fields>InvalidClicks</fields><fields>InvalidClickRate</fields></selector><reportName>Account performance report #5c98350389fef</reportName><reportType>ACCOUNT_PERFORMANCE_REPORT</reportType><dateRangeType>TODAY</dateRangeType><downloadFormat>XML</downloadFormat></reportDefinition>

**Comment by rezetta** [comment] 2019-03-26 08:38
Yeah, it seems very random.

**Comment by fiboknacky** [comment] 2019-03-27 09:25
Hello @rezetta 

I've tried downloading reports for all the client accounts you mentioned in sequence, but couldn't reproduce the issue.
The report definition you provided results in quite a small result for each account too.
So, I won't expect any time-out issues to occur by that.

The only workaround would be you'd need to handle such an issue by retrying after a certain amount of time.

Best,
Knack

**Comment by rezetta** [comment] 2019-03-27 09:32
Ok, but it's still an issue.
Could it be network related?

**Comment by fiboknacky** [comment] 2019-03-27 09:45
Yes, it could be. There are many factors that can affect this issue like internet connections between your locations and the servers. I've seen some cases when a user of a certain country couldn't connect to the servers at all, and then the issue went away without any fix on either side.
Unfortunately, unless you face this issue continuously for every report downloading, it'd be hard to reproduce the issue on our side.

**Comment by rezetta** [comment] 2019-03-27 09:49
Okey, but still. The issue is continuously for every report we try to
download. It started last friday and we had no changes prior to this error.
So I am a little confused. I have sent an inquiry to our network team.

**Comment by fiboknacky** [comment] 2019-03-27 10:01
You've said that it happens only for some accounts randomly.
Is there any time you see this for all the accounts you request?

Seeking help from network team would be a good way to do.
Another way that would help is to try downloading reports from outside your current network, using a different computer/server.

**Comment by rezetta** [comment] 2019-03-27 10:10
Correct, there is no consistency in which accounts fail. So it is not a
problem with the client account, but rather an error in our network or
Google's network.
We download all the data for every account, every night.

**Comment by rezetta** [comment] 2019-03-27 10:49
Okey, now I moved outside our network and I still get errors.

But now it shows:
Error:
Error creating resource: [message] fopen(): SSL: Success

**Comment by fiboknacky** [comment] 2019-03-27 10:58
That looks weird. Can you try other computers too please?
That error occurs for all accounts or still some accounts randomly?

**Comment by rezetta** [comment] 2019-03-27 11:10
Tried to run it again and it stops at a new clientId each time, which to me
means it's random.

**Comment by rezetta** [comment] 2019-03-27 11:38
I have tried 3 separate networks / ISPs, still the same issue.

**Comment by fiboknacky** [comment] 2019-03-27 12:14
Can you try on fresh computers by just running our [code example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Reporting/DownloadCriteriaReportWithSelector.php) multiple times on different client customer IDs?

**Comment by rezetta** [comment] 2019-03-27 12:33
I used a freshly installed VM on the last attempt. I can download the code
example there and run it multiple times.

**Comment by rezetta** [comment] 2019-03-27 12:36
So I did and it failed.

Error:
Client error: `POST
https://adwords.google.com/api/adwords/reportdownload/v201809` resulted in
a `400 Bad Request` response

PHP Fatal error:  Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException:
Details: [fieldPath: selector.reportDefinition; trigger: ; errorString:
ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH] in
vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201809/ReportDownloader.php:234

**Comment by fiboknacky** [comment] 2019-03-27 12:39
That error occurs because you're trying to download reports from the manager accounts.
Report downloading can be done on client accounts only.

**Comment by rezetta** [comment] 2019-03-27 12:41
Okey, so I tried some other clientIds. Some work.. But every so often they
fail with the same error as before.

This is confusing and we need a solution to this problem.

**Comment by fiboknacky** [comment] 2019-03-27 12:46
Have you tried what I mentioned above: retrying after a certain amount of time?
I know that it's not a solution for you, but it's a good workaround in many cases.

**Comment by fiboknacky** [comment] 2019-03-27 12:46
Have you tried what I mentioned above: retrying after a certain amount of time?
I know that it's not a solution for you, but it's a good workaround in many cases.

**Comment by rezetta** [comment] 2019-03-27 12:49
Of course. I also tried setting sleep(5) after each request.

**Comment by afbora** [comment] 2019-03-28 07:19
@fiboknacky I found the issue with log exceptions while connecting api. So my account is basic for now and have a limits:

> [fieldPath: ; trigger: Basic Access Daily Reporting Quota; errorString: RateExceededError.RATE_EXCEEDED]

@rezetta Your account is basic or standart? Maybe this is the reason for your errors.

Documentation: https://developers.google.com/adwords/api/docs/guides/rate-limits

**Comment by fiboknacky** [comment] 2019-03-28 07:24
@afbora 

That is probably different issue.
You'd need to slow down your requests when you hit the rate limit error.

**Comment by afbora** [comment] 2019-03-28 07:27
@fiboknacky I know. I will apply for standart access.

@rezetta's response and mine is same. I guess it could be the same error?

**Comment by fiboknacky** [comment] 2019-03-28 07:36
From what he shared, I don't see he got the same error yet:

```
[fieldPath: ; trigger: Basic Access Daily Reporting Quota; errorString: RateExceededError.RATE_EXCEEDED]
```

But yes, it's good to confirm here again too. :-)

The bad request can happen when you hit the rate limit like in your case.
Or it can be just networking issues.
In case of the rate limit, I usually see the error you got rather than something like that @rezetta got below:

```
Error:
Error creating resource: [message] fopen(): Failed to enable crypto
[file] /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201809): failed to open stream: operation failed
[file] /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
```

**Comment by afbora** [comment] 2019-03-28 07:45
@fiboknacky You right!, i got that.

So this could be about SSL verify (Failed to enable crypto)?

@rezetta's options dont verify ssl. Here my request options:

```
$options = [
    'stream_context' => [
        'http' => [
            'timeout' => 60
        ],
        'ssl' => [
            'verify' => storage_path('certificates/cacert.pem')
        ],
        'curl' => [
            CURLOPT_SSLVERSION => 3
        ]
    ]
];
```

**Comment by rezetta** [comment] 2019-03-28 08:17
I have the extended account with no limits.

**Comment by fiboknacky** [comment] 2019-04-01 06:18
So, definitely this is a different issue.

**Comment by chiragvels** [comment] 2019-07-01 09:48
@rezetta ,

You found any solution to this issue?

I was facing same from last couple of days.

Thanks,

**Comment by andreladocruz** [comment] 2019-08-08 18:39
@fiboknacky ,

We are having the same issue here in the last days.

Looking here https://developers.google.com/adwords/api/docs/common-errors we can´t the error description.

Any help?

**Comment by rezetta** [comment] 2019-08-08 18:43
Have you tried the steps mentioned above?

tor. 8. aug. 2019, 20:39 skrev André Lado Cruz <notifications@github.com>:

**Comment by andreladocruz** [comment] 2019-08-08 18:51
The error we are receiving is

clientCustomerId=6128200354 unknown (AwApi-PHP, googleads-php-lib/42.0.0, PHP/7.3.7-1+ubuntu19.04.1+deb.sury.org+1, GuzzleHttp/6.3.3, curl/7.64.0) "POST /api/adwords/reportdownload/v201809 HTTP/1.1" Status: 400

and we have 36 different customer´s ids involved.

The question is, why this is throwing an error randomly throughout the day?

**Comment by fiboknacky** [comment] 2019-08-13 07:13
@andreladocruz  There was an outage during last week, which seems to be fixed already.
Could you confirm again?

**Comment by andreladocruz** [comment] 2019-08-13 10:40
@fiboknacky , 

We found that we were reaching request limits. We increased the check interval and upgraded our account from Basic to Standard.

Everything working fine since then.

Thanks for the reply! =)

**Comment by fiboknacky** [comment] 2019-08-14 07:46
Thanks for confirming.
@rezetta  Sorry that the thread is getting long and we probably lose track a bit.
Do you still need any help from our side?

**Comment by fiboknacky** [comment] 2019-08-30 10:23
Closing due to inactivity.

**Closed by fiboknacky** 2019-08-30 10:23 UTC
Labels: P2

**Comment by rezetta** [comment] 2019-08-30 10:37
I have been on vacation, so a little late answer.

No - this issue resolved it self... So my guess is that something was corrected in the other end (Google)..

**Comment by fiboknacky** [comment] 2019-08-30 10:49
Thanks for getting back to us, anyway. :-D

**Comment by rezetta** [comment] 2019-08-30 10:59
Thanks for the help! :-D
