### ISSUE TITLE
Problem with conversion trackers and pagination

### ISSUE THREAD

**Issue by giorrrgio** [googleads/googleads-php-lib#592] opened 2019-05-30 16:23 UTC
I'm working with `ConversionTrackerService`to get a list of the conversion actions associated to a customer. I'm doing the following request:

```
        $service = $this->services->get($this->session, ConversionTrackerService::class);
        $selector = new Selector();
        $selector->setFields([
                'Id',
            ])
            ->setPaging(0, 10));

        if (null !== $sortField) {
            $selector->setOrdering([new OrderBy($sortField, $sortOrder)]);
        }

        $pageResult = $this->statsTracker->tracedRun(function () use ($service, $selector) {
            return $service->get($selector);
        }, 'api', 'ConversionTrackerService.get');
```

With some customers it returns 0 results even if a bunch of conversion actions are configured, but if I remove the pagination it returns the expected number of results. 
With other accounts everything's fine. Do you have any hints to investigate further?
Thanks

**Comment by fiboknacky** [comment] 2019-05-31 14:05
Could you give your client customer ID as well?
Thanks.

**Comment by giorrrgio** [comment] 2019-06-04 14:27
Hai @fiboknacky, the affected customer Id is 1715823800
Let me know if you need further info.
Thank you

**Comment by fiboknacky** [comment] 2019-06-25 10:32
Hello, 

I'm sorry for taking long time.
I could reproduce the issue, but it seems to be more related to the AdWords API itself, not the client library.

Could you please either provide your email here (and I can remove it to prevent spam) so I can contact you via our product support channel or post a topic on [the forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) and refer to this bug?

Thanks!

**Comment by giorrrgio** [comment] 2019-07-01 15:36
@fiboknacky giorgio dot cefaro at hootsuite.com

Thanks!

**Comment by fiboknacky** [comment] 2019-07-02 04:45
Not sure what you meant. Could you please type in English again? Thank you.

**Comment by giorrrgio** [comment] 2019-07-11 17:46
> Not sure what you meant. Could you please type in English again? Thank you.

Sorry, it was just a masked email address :-)
giorgio.cefaro@hootsuite.com

**Comment by fiboknacky** [comment] 2019-07-12 07:24
Hello,

I've sent an email to you. Please let me know if you don't receive it after some time.
Let's follow up there and I'll close this issue for now.

Best,
Knack

**Closed by fiboknacky** 2019-07-12 07:24 UTC
