### ISSUE TITLE
MANY Issues - especially ExpandedTextAds.

### ISSUE THREAD

**Issue by sylvainmtl68** [googleads/googleads-php-lib#197] opened 2016-12-24 16:35 UTC
Hi!

I just tried to run the AddCompleteCampaignsUsingBatchJob.php to get an overview of the various changes in the new library.  When I tried that same script in the old library last, it went very smoothly, not this time with the new library.

Here are some issues I encountered, in my 2 hours of testing that file and trying to make it work.

- I had to comment out part of the BatchJobsDelegate.php file because it couldn’t find the GuzzleLogMessageHandler apparently.  (yet, I installed the new library with Composer and all the files seem to be there, including the ones from Guzzle.

- In the keywords part, you add «!!! », which causes the keyword to be rejected due CriterionError.KEYWORD_HAS_INVALID_CHARS

- You forgot to use Google\AdsApi\AdWords\v201609\cm\ExpandedTextAd in the batch processing file.

- Then in the ExpandedTextAd part, you call for function setHeadline(), but it doesn’t exist… the functions are called setHeadlinePart1() and setHeadlinePart2().

- Inversely, the script calls for setDescription1() and setDescription2(), but it’s only setDescription().

- Still in the ExpandedTextAd section… you try to see the DisplayUrl and FinalUrls, but there are no functions defined in the ExpandedTextAd class for that and we get an error saying we cannot define those.  

I tried to tweak it out, but I couldn’t make it work.  I looked at the examples section in the AddExpandedTextAds.php file, and the code there to create ExpandedTextAds doesn’t work either.

So, totally unable to create text ads… none of the provided examples work.

**Comment by fiboknacky** [comment] 2016-12-24 17:25
Hello @sylvainmtl68,

I'm really sorry for your inconvenience.
We'll work on the fix very soon.

As for the keywords part, we deliberately add !!! for 50% of keywords created just to demonstrate how the `BatchJobService` and `BatchJobs` deal with such a case.
So this works as intended. If you wish to create valid keywords, please modify that method accordingly.

For other issues, I'll work on a fix and push to the repo later.

Best,
Knack

**Comment by sylvainmtl68** [comment] 2016-12-24 17:45
Thanks.

yes, I just read the header of the buildAdGroupCriterionOperations that
explains it.  It's just that as I ran that same file in the previous
library and it went smoothly, I wasn't expect any errors put there on
purpose... I had assumed the previous file had just been migrated to the
new library methods.

But it's okay... it's not a real issue... not like the issues with the
ExpandedTextAds which really affect the behaviour of the library, those are
the important issues.

2016-12-24 14:26 GMT-03:00 Thanet Praneenararat <notifications@github.com>:

**Comment by sylvainmtl68** [comment] 2016-12-24 18:00
I forgot to mention... that if I wanted to try out this batch processing
file it's because the one of the old version had issues with the return
values when we included campaign extensions.  I wanted to see if that
problem has been fixed with the change of XML deserializer.  I have about
8000 campaigns to launch for a client this week... and I'd much prefer use
the batch process... but without the ability to receive the campaign
numbers and error notifications when I include Campaign Extensions, I will
have to create the campaigns one by one.

2016-12-24 14:45 GMT-03:00 Sylvain Beauregard <sylvainmtl68@gmail.com>:

**Comment by fiboknacky** [comment] 2016-12-24 18:03
Hi Sylvain,

Thanks for more information.
Would you mind clarifying more what kinds of issues you're faced with when you include campaign extensions?
Is it similar to issue #192?

Regards,
Knack

**Comment by sylvainmtl68** [comment] 2016-12-24 18:13
Yes, similar to this.  Sometimes  the error was regarding the
CallOutFeedItem object.

By trying various scenarios, I was able to get rid of those two messages by
creating since I saw it was mentionning of array and I was creating
multiple extensions at once...I decided to create multiple instances of
CampaignExtensionSetting (one for each sitelink) rather than using the
collection campaignExtensionSetting->extensionSetting->extensions.

That got rid of the SitelinkFeedItem and CalloutFeedItem errors... but then
it gave me another one I couldn't figure out...

*error*:  Call to a member function setAccessible() on null in
*/home/dealerbreacher/googleads-php-lib-master_oldone/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php*
on line *140*

When I was pushing multiple extensions at once... they were created
perfectly in  AdWords... it was just the processing of AdWords' response
that wasn't correct.  Which was very frustrating because I knew my
campaigns were created perfectly, but I couldn't receive their numbers to
store (for example).

When I split up to make one CampaignExtensionSetting per extension, only
one was created.


2016-12-24 15:03 GMT-03:00 Thanet Praneenararat <notifications@github.com>:

**Comment by fiboknacky** [comment] 2016-12-26 07:29
Hi @sylvainmtl68 

Thanks for more information.

Regarding the `CallOutFeedItem` issue, this occurs only in the old XML deserializer because it still uses the classes manually added by ourselves.
The deserializer in this new version makes use of the batch job related classes generated by WSDL, just similar to other classes related to SOAP services.

As for
> *error*:  Call to a member function setAccessible() on null in
> */home/dealerbreacher/googleads-php-lib-master_oldone/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php*
> on line *140*

I found that mostly it's because users get SOAP services' [ApiError](https://github.com/googleads/googleads-php-lib/blob/deprecated/src/Google/Api/Ads/AdWords/v201609/CampaignService.php#L41) mixed with reporting [ApiError](https://github.com/googleads/googleads-php-lib/blob/deprecated/src/Google/Api/Ads/AdWords/Util/v201609/ReportClasses.php#L37).
This is unfortunately confusing because we didn't support namespacing in [the deprecated branch](https://github.com/googleads/googleads-php-lib/tree/deprecated) yet.

Clearly doing `require_once` for only classes related to SOAP services or classes related to reporting would resolve such as issue.

FYI, as for the main issue you've reported, we're working on the fix.

Cheers,
Knack

**Comment by vtsao** [comment] 2017-01-11 17:36
These issues are fixed in [release v25.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.1.0).

**Closed by vtsao** 2017-01-11 17:36 UTC
Labels: bug
