### ISSUE TITLE
Follow up on #342

### ISSUE THREAD

**Issue by brstgt** [googleads/googleads-php-lib#344] opened 2017-08-23 09:56 UTC
Sorry. I still cannot comment and as you closed the issue answering per mail is also not possible. So this way. What I wanted to add:

Maybe you did not fully understand my intention.
This edge case would still be possible with a component oriented package architecture! You can install as many (Server-)API versions as you want by adding multiple dependencies in composer.

A composer file could look like this:

```
{
    "require": {
        "googleads/googleads-adwords-201702": "^28.0",
        "googleads/googleads-adwords-201705": "^28.0",
        "googleads/googleads-dfp-201705": "^28.0"
    },
}
```

Sure - I can create a shell script but this is not a proper approach. It is a hack.

**Comment by dklimkin** [comment] 2017-08-23 13:25
Hello brstgt,

Yes, I understand. There is though a significant amount of overlapping code in 'googleads-adwords-201702' and 'googleads-adwords-201705' as well as 'googleads-adwords-201705' and 'googleads-dfp-201705'. Splitting like this would require a separate package 'googleads-common' as a common dep and this is a non-trivial refactoring.

This will also break usage pattern for many existing users -- something we always try to avoid.

We'll definitely keep this in mind going forward but we would not undertake it right now.

**Comment by brstgt** [comment] 2017-08-23 14:05
I did not expect to change that instantly! Of course this is sth that has
to be placed on a roadmap.

2017-08-23 15:25 GMT+02:00 Danial Klimkin <notifications@github.com>:

**Comment by fiboknacky** [comment] 2017-09-26 09:07
Hi Benjamin,

Thanks for your feedback once again. 
I'm going to close this for now as it's not a bug, but we'll surely keep this in mind for our road map.

Best,
Knack

**Closed by fiboknacky** 2017-09-26 09:07 UTC
