### ISSUE TITLE
How to get data by Internet.

### ISSUE THREAD

**Issue by shanglei001** [googleads/googleads-php-lib#431] opened 2017-12-27 02:53 UTC
Hi,
At the beginning of learning API, we built API text and executed console,
cd /googleads-php-lib/examples/AdWords201710/BasicOperations/
php GetCampaigns.php to get data.
But how do we get data by Internet?
What should we do if we need to get some data about AD by visiting  
https://adwords.zjchuhai.com/test.php 

 to revert some data by Adwords.
Steps as follows:
1. Copy the document
/googleads-php-lib/examples/AdWords/v201710/BasicOperations/GetCampaigns.php to root directory.
2. Revise  GetCampaigns.php to test.php
3. Revise the content  require __DIR__ . '/../../../../vendor/autoload.php';_ of test.php to _require './googleads-php-lib/vendor/autoload.php';_
4. Visiting https://adwords.zjchuhai.com/test.php 

 should output the data we need. But Number of results found: 0, the log has not been written. We could not find the data by API text.

Thinks

**Comment by fiboknacky** [comment] 2017-12-27 06:51
Hello @shanglei001 

If you would like to try our examples, I recommend to read [this guide](https://github.com/googleads/googleads-php-lib#downloading-a-compressed-tarball) first.
Downloading via a tarball is probably easiest way for you. :)

Having said that, it seems you've been able to run the example via your web app.
But the issue is you don't see any results returned.
This can happen from many factors, such as the selector fields condition you use, the client customer ID you specify.

I guess the issue would be the latter. Could you please double check if you specify the correct `clientCustomerId` in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L5)?

For further help regarding AdWords in general, I suggest to post your question in our [AdWords API forum](https://groups.google.com/d/forum/adwords-api).

Thank you!

Cheers,
Knack

**Comment by shanglei001** [comment] 2017-12-27 09:13
Hello Knack
I guess this is the reason，I see in the API documentation

`// Create an AdWordsUser instance using the default constructor, which will load
// information from the auth.ini file as described above.
$user = new AdWordsUser();
$user->SetClientCustomerId('123-456-7890');`

But I did not find it “AdWordsUser” Class

**Comment by fiboknacky** [comment] 2017-12-27 09:51
Hello @shanglei001 

It looks like you're looking at the old version of the library.
Please find the latest version [here](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201710/BasicOperations/GetCampaigns.php).

Best,
Knack

**Comment by shanglei001** [comment] 2017-12-28 01:07
Hello Knack

I use this one.
How to specify `clientCustomerId` ?

Thinks

**Comment by shanglei001** [comment] 2017-12-28 01:56
I was so surprised, I actually succeeded. `https://github.com/googleads/googleads-php-lib/issues/209` helped me. 
Thanks again!

**Comment by fiboknacky** [comment] 2017-12-28 03:57
Hello @shanglei001 

Glad that you can find the way to do so.
That's a programmatical way of setting the value.

> I guess the issue would be the latter. Could you please double check if you specify the correct clientCustomerId in this line?

As I mentioned in the first reply, you could do so via `adsapi_php.ini` too.

> But, https://developers.google.com/adwords/api/docs/guides/start is too old.

Could you please point out where in the doc is too old? I still find it's up-to-date.
Thanks!

Best,
Knack

**Comment by shanglei001** [comment] 2017-12-28 05:19
Hello Knack

I'm building an environment from `https://developers.google.com/adwords/api/docs/guides/start` .
But I have many customers, They all need to use their own `ClientCustomerId`.
So I found it :

`// Create an AdWordsUser instance using the default constructor, which will load
// information from the auth.ini file as described above.
$user = new AdWordsUser();
$user->SetClientCustomerId('123-456-7890');`

It bothered me for a long time. It's like what you see. `https://github.com/googleads/googleads-php-lib/issues/209` helped me.
Because he is using 
`$ session = (new AdWordsSessionBuilder ())
         -> fromFile ()
         -> withOAuth2Credential ($ oAuth2Credential)
         -> withClientCustomerId ('123-456-7890')
         -> build (); `
This form.
So for a newbie it's important. Because from the API documentation can not solve the problem, even if it is the most basic.

Think you Knack, Think you for your reply.

**Comment by fiboknacky** [comment] 2017-12-28 05:54
> So I found it :
// Create an AdWordsUser instance using the default constructor, which will load // information from the auth.ini file as described above. $user = new AdWordsUser(); $user->SetClientCustomerId('123-456-7890');

Where did you find the above sentence?
I can't find it in https://developers.google.com/adwords/api/docs/guides/start

Thanks!

**Comment by shanglei001** [comment] 2017-12-28 05:55
https://developers.google.com/adwords/api/docs/guides/samples-use-cases

**Comment by fiboknacky** [comment] 2017-12-28 06:15
I see why you're confused. You're looking at the Chinese pages right?
It looks like they're not updated yet. I'll make sure that they're updated soon.

**Comment by shanglei001** [comment] 2017-12-28 06:19
Haha, yes man, was discovered by you. Is there an English version?

**Comment by fiboknacky** [comment] 2018-01-05 09:27
You can select the language at the bottom-left of all pages in our website.
Meanwhile, I'll note this and fix this soon. For now, as it's not related to this library, I'll close this issue.

Best,
Knack

**Closed by fiboknacky** 2018-01-05 09:27 UTC
