### ISSUE TITLE
Cannot redeclare class DateTimeUtils

### ISSUE THREAD

**Issue by Jafo232** [googleads/googleads-php-lib#241] opened 2017-02-15 15:30 UTC
All of a sudden I am having this issue when calling new StatementBuilder();  I temporarily fixed it in our production by modifying Pql.php from:

    require_once 'Google/Api/Ads/Dfp/Util/v201611/DateTimeUtils.php';

To:

    if (!class_exists('DateTimeUtils'))
	require_once 'Google/Api/Ads/Dfp/Util/v201611/DateTimeUtils.php';

**Comment by vtsao** [comment] 2017-02-15 15:35
Hi @Jafo232 which version of the library are you using?

**Comment by vtsao** [comment] 2017-02-21 18:35
This is also strange because require_once should prevent this. If you're still running into issues with this, please give me a summary of what your code looks like so I can try to reproduce. Closing this for now.

**Closed by vtsao** 2017-02-21 18:35 UTC
Labels: old library
