### ISSUE TITLE
Small error with PHPDoc: long[] should be int[]?

### ISSUE THREAD

**Issue by komirad** [googleads/googleads-php-lib#261] opened 2017-03-27 00:57 UTC
In FeedItemAttributeValue, some values are defined as `long[]` when they should be `int[]`. For example, [line 179](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201702/cm/FeedItemAttributeValue.php#L179).

It probably doesn't affect functionality but my IDE is displaying a warning.

**Comment by fiboknacky** [comment] 2017-03-27 02:15
Hi JC,

Thanks for reporting.
It's generated from the WSDL file [as described here](https://developers.google.com/adwords/api/docs/reference/v201609/FeedItemService.FeedItemAttributeValue#integervalue).

As it's a `INT64` value, which is equivalent to `long`, this works as intended from this library aspect.
I'll talk with my colleagues to see why this is named `integerValue`, not `longValue`.

Cheers,
Knack

**Comment by fiboknacky** [comment] 2017-03-29 03:57
To clarify, from the library aspect, it works as intended.
So, I'll close this issue soon.

**Comment by komirad** [comment] 2017-03-29 04:17
Just being curious. Can you clarify the purpose of the PHPDoc for the library? I see that on AdWordsNormalizer, it uses the doc block for instantiating objects, is this related?

As far as I understand PHPDoc is mainly used to aid IDEs in interpreting code. And in this case long[] is not a valid PHP variable [type](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types) or a class in the library, I would think int[] should be used.

**Comment by fiboknacky** [comment] 2017-03-29 05:32
Hi @komirad 

AdWordsNormalizer is not related to how the classes under `src/AdsApi/AdWords/vXXXXXX` are generated at all.
Classes in those directories were generated by our modified `wsdl2phpgenerator`.

> And in this case long[] is not a valid PHP variable type or a class in the library, I would think int[] should be used.
Ah, I missed this point. Then your argument is valid that we should change the PHPDoc to generate `int` for `INT64` type of WSDL.
Let's keep this open until I fix this.

Thanks again.

Best,
Knack

**Comment by fiboknacky** [comment] 2017-06-30 10:01
This is fixed in [v28.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/28.0.0).

**Closed by fiboknacky** 2017-06-30 10:01 UTC
