### ISSUE TITLE
Disable info messages during execution

### ISSUE THREAD

**Issue by googlogmob** [googleads/googleads-php-lib#444] opened 2018-01-28 07:18 UTC
How to disable such message?

`[2018-01-27 17:26:20] AW_REPORT_DOWNLOADER.INFO: clientCustomerId=173-137-7173 unknown (AwApi-PHP, googleads-php-lib/32.1.0, PHP/7.2.1-1+0~20180105151221.16+jessie~1.gbpd3910a, GuzzleHttp/6.2.1, curl/7.38.0) "POST /api/adwords/reportdownload/v201710 HTTP/1.1" Status: 200
`

**Comment by fiboknacky** [comment] 2018-01-29 07:21
Hello,

You can see how to configure logging [in this section](https://github.com/googleads/googleads-php-lib#configuring-logging).
In particular, you can mimic what we do in [AdsLoggerFactory](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsLoggerFactory.php#L39), but use [NoopHandler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NoopHandler.php) instead of `StreamHandler`.

Best,
Knack

**Comment by fiboknacky** [comment] 2018-01-31 19:42
Seems you don't have further issue on this, so I'll close this for now.
Please let me know if you need further help.

**Closed by fiboknacky** 2018-01-31 19:42 UTC
Labels: P2

**Comment by nadorator** [comment] 2018-12-21 10:40
I have a similar problem and don't want to use NoopHandler because I want to have the other message except the INFO. Right now my code his:

`$LoggerInterface = $adsLoggerFactory->createLogger('', fopen("./logs.txt","w"), Logger::WARNING);`

But I have nothing in the log file and the INFO from guzzle still are displayed on stdout instead of stderr. As it is a batch jobs with thousands of guzzle request my stdout is a total mess because of that. Also the result is sent by email and then the email is too huge to be sent.  Do you have another idea instead of using NoopHandler ?

**Comment by fiboknacky** [comment] 2018-12-21 11:47
How did you set the created logger to the AdWordsSessionBuilder?
Could you please show that to me?

Thanks.
Knack

**Comment by nadorator** [comment] 2018-12-24 11:58
Here is the code I used in my adwordSessionBuilder:
` $session = (new AdWordsSessionBuilder())
                ->withDeveloperToken(CONFIG_GAPI_DEVELOPER_TOKEN)
                ->withClientCustomerId($row['GoogleID'])
                ->withUserAgent(CONFIG_GAPI_USERAGENT)
                ->withOAuth2Credential($oAuth2Credential)
                ->withReportSettings($reportSettings)
                ->withSoapLogger($LoggerInterface)
                ->build()
            ;
`

**Comment by fiboknacky** [comment] 2018-12-25 10:19
If you would like to set the batch job logger, you need to use [`withBatchJobsUtilLogger`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L379), not `withSoapLogger`.

Cheers,
Knack

**Comment by fiboknacky** [comment] 2019-01-07 11:10
Do you want to manipulate the batch job logs or reporting logs?
From your last message, I understood that it's the former, but it seems the latter. :)

If you want to manipulate the reporting logs, of course, setting `$LoggerInterface` wouldn't work.
You would need to use [withReportDownloaderLogger](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L364) instead.

**Comment by nadorator** [comment] 2019-01-16 09:45
First, I appreciate a lot the support and effort thanks. 

We have around 6000 adwords clients account in our google management main account. We use the adwords api to have the reporting of each clients in a loop. It is a batch job process in php on the command line. 

We use the reporting resuults in CSV into an array to extrapolate the budget spent by us for our clients and really used in adwords. Then we send the reults by mails in excel files to our adwords manager in our company.

We display every error/bug/warning on the stdout of the command line. Then this output is sent by email to the server administrator to verify all scripts are still functioning. 

The problem is only the guzzle Info response saying that the url is ok with a 200 status because this info message is displayed for each report on the outpout of the command line and then the mail sent to the administrator is too heavy for his mailbox because we have 6000 clients and this script is running every day.

We just want to hide the INFO from guzzle to not have anymore those unnecessary logs saying "all is fine"... 

so all we need is to have no more INFO from guzzle at all. only WARNINGS.

what logger should i use then and how to use it because in my past example nothing was working...

**Comment by fiboknacky** [comment] 2019-01-16 10:03
Sorry. But I'm kind of confused now.
Do you want to change report logging or batch job logging or both?
You've mentioned both cases in replies above. Could you confirm again please?

**Comment by nadorator** [comment] 2019-01-16 12:39
Previously we were using report logging. But you suggested to change to batchjob logging because we are in the batch job process in command line. 

In both case, report logging or batch job logging , we still have guzzle info message  on the standard output. We don't want guzzle info message at all whatever the logging class is. 

In fact I don't understand why we have guzzle info message as we specified that we only want the warnings. 

When we use report logger the message is not the same than when we use the backjob logger but both message are INFO and we don't want info. Before switching to adwords api version 2018x the INFO message where not displayed. 

I only want to hide this: " AW_REPORT_DOWNLOADER.INFO: clientCustomerId=2729055379 Proximedia Nederland B.V.: AdWords API PHP get info CRONJOB (AwApi-PHP, googleads-php-lib/38.0.0, PHP/7.1.22, GuzzleHttp/6.3.3, curl/7.61.1, ReportDownloader/string) "POST /api/adwords/reportdownload/v201809 HTTP/1.1" Status: 200" completly.

**Comment by fiboknacky** [comment] 2019-01-16 14:46
Could you share your most recent code for building `AdWordsSession` object now?
Do you use what I suggested in [this reply](https://github.com/googleads/googleads-php-lib/issues/444#issuecomment-451901454) yet?

I recommended you to use batch job logger because you mentioned that you use batch jobs.
I begin to not sure if you batch jobs and my batch jobs are the same. :)
Batch jobs I mean is the feature of AdWords API, which you can see more detail in [this guide](https://developers.google.com/adwords/api/docs/guides/batch-jobs).

**Comment by nadorator** [comment] 2019-01-16 14:50
No problem i will show you all the code so you'll understand cleary :) also indeed it was not the same batch jobs then :p 

here the baby: `#!/usr/local/bin/php
<?php

namespace cron\google\jobs;

$timer_start = time();

// REQUIRED SCRIPTS -------------------------------------------------------------------------

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/tools.php';
require_once __DIR__ . '/vendor/autoload.php';

use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;
use Google\AdsApi\AdWords\Reporting\ReportDownloadResult;
use Google\AdsApi\AdWords\Reporting\v201809\DownloadFormat;
use Google\AdsApi\AdWords\Reporting\v201809\ReportDefinition;
use Google\AdsApi\AdWords\Reporting\v201809\ReportDefinitionDateRangeType;
use Google\AdsApi\AdWords\Reporting\v201809\ReportDownloader;
use Google\AdsApi\AdWords\ReportSettingsBuilder;
use Google\AdsApi\AdWords\v201809\cm\ReportDefinitionReportType;
use Google\AdsApi\Common\AdsLoggerFactory;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\v201809\cm\Selector;
use Google\AdsApi\Common\OAuth2TokenBuilder;
use Monolog\Logger;

// REQUIRED CONFIG --------------------------------------------------------------------------

# To view XML request/response, change value of $debug to > 0.
# Timers are printed on debug > 0.
$debug = 0;
const PAGE_LIMIT = 500;
const MAX_THREADS = 25;
const PAGE_SIZE = 10;

// REQUIRED FUNCTIONS -----------------------------------------------------------------------

function printAccountHierarchy($account, $customerIdsToAccounts, $customerIdsToChildLinks, $depth = null)
{
    if ( $depth === null )
    {
        print "(Customer ID, Account Name)\n";
        printAccountHierarchy($account, $customerIdsToAccounts, $customerIdsToChildLinks, 0);
        return;
    }

    print str_repeat('-', $depth * 2);
    $customerId = $account->getCustomerId();
    printf("%s, %s\n", $customerId, $account->getName());

    if ( array_key_exists($customerId, $customerIdsToChildLinks) )
    {
        foreach ( $customerIdsToChildLinks[strval($customerId)] as $childLink )
        {
            $childAccount = $customerIdsToAccounts[strval($childLink->getClientCustomerId())];
            printAccountHierarchy($childAccount, $customerIdsToAccounts, $customerIdsToChildLinks, $depth + 1);
        }
    }
}

function mail_attachment($filename, $filecontent, $mailto, $from_mail, $from_name, $replyto, $subject, $message)
{
    // Create the Transport
    $transport = (new \Swift_SmtpTransport('localhost', 25));

    // Create the Mailer using your created Transport
    $mailer = new \Swift_Mailer($transport);

    // Create a message
    $message = (new \Swift_Message($subject))
        ->setFrom([$from_mail => $from_name])
        ->setTo([str_replace('"','',str_replace('@mail.proxirepair.be','',$mailto)) => 'A name'])
        ->addReplyTo($replyto)
        ->setBody($message)
        ->attach(new \Swift_Attachment($filecontent,$filename,"text/csv"))
    ;

    if ( defined('CONFIG_ADWORDSREPORT_MAILS') && count(unserialize(CONFIG_ADWORDSREPORT_MAILS)) > 0 )
    {
        $arr = unserialize(CONFIG_ADWORDSREPORT_MAILS);
        foreach ( $arr as $email )
        {
            $message->addCc(trim($email));
        }
        $message->addCc('nadir@proximedia.be');
    }
    else
    {
        $message->addCc('nadir@proximedia.be');
    }

    // Send the message
    $result = $mailer->send($message);
    if ( !$result )
    {
        echo "mail send ... ERROR!".print_r(error_get_last(),true)."\r\n";
    }
}

// ACTUAL SCRIPTS ---------------------------------------------------------------------------

date_default_timezone_set('Europe/Brussels');

if ( $debug > 0 )
{
    echo("START TIME: " . date('Y-m-d H:i:s') . "\n");
}
else
{
    error_reporting(error_reporting() & ~E_WARNING);
}

try
{
    $margin = 0.15;
    $expectedWeeks = 30.5/7;
    $elapsedWeeks=1;

    //dBase connection
    $conn= DriverManager::getConnection([
        'host' => SERVER_DBASE,
        'dbname' => NAME_DBASE,
        'user' => LOGIN_DBASE,
        'password' => PASS_DBASE,
        'driver' => 'pdo_mysql',
        'charset' => 'utf8',
        'driverOptions' =>[
            1002=>'SET NAMES utf8'
        ],
    ],new Configuration());

    // Generate a refreshable OAuth2 credential for authentication.
    $oAuth2Credential = (new OAuth2TokenBuilder())
        ->withClientId(CONFIG_GAPI_CLIENT_ID)
        ->withClientSecret(CONFIG_GAPI_CLIENT_SECRET)
        ->withRefreshToken(CONFIG_GAPI_REFRESH_TOKEN)
        ->build()
    ;

    // See: ReportSettingsBuilder for more options (e.g., suppress headers)
    // or set them in your adsapi_php.ini file.
    $reportSettings = (new ReportSettingsBuilder())
        ->skipReportHeader(false)
        ->skipColumnHeader(false)
        ->skipReportSummary(false)
        ->useRawEnumValues(false)
        ->includeZeroImpressions(true)
        ->build()
    ;

    // Create Soap Logger Interface to supress INFO messages on the console
    $adsLoggerFactory = new adsLoggerFactory();
    $LoggerInterface = $adsLoggerFactory->createLogger('', null, Logger::INFO);

    // See: AdWordsSessionBuilder for setting a client customer ID that is
    // different from that specified in your adsapi_php.ini file.
    // Construct an API session configured from a properties file and the OAuth2
    // credentials above.

    $reportDefinition = new ReportDefinition();

    $reportDefinitionSelector = new Selector();
    $reportDefinitionSelector->setFields(['Cost']);

    $reportDefinition->setSelector($reportDefinitionSelector);
    $reportDefinition->setReportName('Customer total costs #' . time());
    $reportDefinition->setDateRangeType(ReportDefinitionDateRangeType::LAST_7_DAYS);
    $reportDefinition->setReportType(ReportDefinitionReportType::ACCOUNT_PERFORMANCE_REPORT);
    $reportDefinition->setDownloadFormat(DownloadFormat::CSV);

    $stmt = $conn->executeQuery('SELECT beup_files.*, beup_users.UserMail FROM beup_files JOIN beup_users ON beup_files.UserId=beup_users.UserId WHERE inMCC="1" AND Category LIKE ">NORMAL" AND BudgetContracted>0 AND CampaignEndDate>NOW() AND CampaignStartDate<"'.date('Y-m-d', strtotime('- 1 month')).'" ORDER BY beup_users.UserMail');

    $toPost = "";

    $headerCSV = '"CustomerId";"Current";"Expected";"Contracted";"Diff";"Manager";"Comment"'.PHP_EOL;
    $cnt = 0;

    while ( $row = $stmt->fetch() )
    {
        try
        {
            // See: AdWordsSessionBuilder for setting a client customer ID that is
            // different from that specified in your adsapi_php.ini file.
            // Construct an API session configured from a properties file and the OAuth2
            // credentials above.

            $session = (new AdWordsSessionBuilder())
                ->withDeveloperToken(CONFIG_GAPI_DEVELOPER_TOKEN)
                //->withClientCustomerId(CONFIG_GOOGE_ID)
                ->withClientCustomerId($row['GoogleID'])
                ->withUserAgent(CONFIG_GAPI_USERAGENT)
                ->withOAuth2Credential($oAuth2Credential)
                ->withReportSettings($reportSettings)
                ->withSoapLogger($LoggerInterface)
                //->withBatchJobsUtilLogger($LoggerInterface)
                ->build()
            ;

            $reportDownloader = new ReportDownloader($session);
            $reportSettingsOverrode = (new ReportSettingsBuilder())
                ->includeZeroImpressions(true)
                ->build()
            ;


            /** @var ReportDownloadResult $reportDownloadResult */
            $reportDownloadResult=$reportDownloader->downloadReport($reportDefinition, $reportSettingsOverrode);
            $data=$reportDownloadResult->getAsString();

            preg_match('/^\\d+$/m', $data, $matches);

            $costsThisMonth = $matches[0]/1000000;
            $costsExpected = $costsThisMonth/$elapsedWeeks*$expectedWeeks;
            $diff = $costsExpected/$row['BudgetContracted']-1;

            if ( abs($diff)>$margin )
            {
                $cnt++;
                $toPost.='"'.$row['CustomerId'].'";"'. $costsThisMonth.'";"'. round($costsExpected,2).'";"'. $row['BudgetContracted'].'";"'. round($diff*100).'%";"'.$row['UserMail'].'";"'. str_replace(";"," ",str_replace('"',"",str_replace("\r",". ",str_replace("\n",". ",str_replace(PHP_EOL,". ",$row['Comment']))))).'";'.PHP_EOL;

            }
            else
            {
                //$cnt++;
                //$toPost.=sprintf('"%s";"%s";"%s";"%s";"%s%%"', $row['CustomerId'], $costsThisMonth, round($costsExpected,2), $row['BudgetContracted'], round($diff*100)).PHP_EOL;
                //echo "false: ";
                //echo sprintf('CustomerId=%s Current=%s Expected=%s Contracted=%s Diff=%s%%', $row['CustomerId'], $costsThisMonth, round($costsExpected,2), $row['BudgetContracted'], round($diff*100)).PHP_EOL;
            }
        }
        catch(\Exception $e)
        {
            echo sprintf('Exception customerId=%s: %s', $row['CustomerId'], preg_replace('/\\s+/', ' ', $e->getMessage())).PHP_EOL;
            continue;
        }
    }

    $mailTo = "";
    $content = "";
    $datas = explode("\n",$toPost);
    foreach ( $datas as $data )
    {
        $line = explode(";",$data);
        if ( trim($line[5])!=$mailTo)
        {
            if ( $mailTo!="" )
            {
                try
                {
                    mail_attachment("report.csv", $headerCSV.$content, $mailTo, "nadir@proximedia.be", "proximedia", "nadir@proximedia.be", sprintf('Techdesk budget warning %s', date('d-m-Y')), "see attachment.");
                }
                catch(Exception $e)
                {
                    echo $e->getMessage();
                }

            }
            $mailTo = trim($line[5]);
            $content = "";
        }
        $content .= ''.trim($line[0]).';'. trim($line[1]).';'. trim($line[2]).';'. trim($line[3]).';'. trim($line[4]).';'. trim($line[5]).';'. trim($line[6]).';'.PHP_EOL;
    }

    if ( $mailTo!="" )
    {
        try
        {
            mail_attachment("report.csv", $headerCSV.$content, $mailTo, "nadir@proximedia.be", "proximedia", "nadir@proximedia.be", sprintf('Techdesk budget warning %s', date('d-m-Y')), "see attachment.");
        }
        catch(Exception $e)
        {
            echo $e->getMessage();
        }
    }

    $toPost2 = '"CustomerId";"Current";"Expected";"Contracted";"Diff";"Manager";"Comment"'.PHP_EOL;
    $toPost = $toPost2.$toPost;
    try
    {
        mail_attachment("report.csv", $toPost, "nadir@proximedia.be", "nadir@proximedia.be", "proximedia", "nadir@proximedia.be", sprintf('Techdesk budget warning %s %s', $row['CustomerId'], date('d-m-Y')), "see attachment.");
    }
    catch(Exception $e)
    {
        $e->getMessage();
    }
}
catch (\Exception $e)
{
    printf("An error has occurred: %s\n", $e->getMessage());
}

if ( CONFIG_UPDATE_MCC_CUSTOMERIDS != "" )
{
    @file_get_contents(CONFIG_UPDATE_MCC_CUSTOMERIDS);
}

if ( $debug > 0 )
{
    echo("RUNNING TIME: " . (time() - $timer_start) . " seconds.\n");
}
exit;`

**Comment by fiboknacky** [comment] 2019-01-16 14:53
Can you format the code so it can be more readable? Thank you.

**Comment by fiboknacky** [comment] 2019-01-16 14:53
Anyway, it seems you haven't done what I suggested in [this reply](https://github.com/googleads/googleads-php-lib/issues/444#issuecomment-451901454) yet.

Could you please do it first?

**Comment by nadorator** [comment] 2019-01-16 15:00
oh yes I have forgotten to test this reply...  I just did it and it seems to work I have no more guzzle log. Thanks a lot :)

**Comment by a-davityan** [comment] 2020-03-19 12:15
To disable report downloader logs do the following.
`->withReportDownloaderLogger(new Logger('AW_REPORT_DOWNLOADER', [new NoopHandler]))`

**Comment by LunarDevelopment** [comment] 2020-11-10 11:00
I'm really late to the party, but anyone else scratching their head on turning off / limiting logging, you could just change the log level in your adsapi_php.ini file to be, say, warning: 

```ini
[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
soapLogLevel = "WARNING"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
; batchJobsUtilLogLevel = "INFO"

```
