### ISSUE TITLE
Intermittent error "Unknown SSL protocol error in connection to accounts.google.com:443" when requesting a report

### ISSUE THREAD

**Issue by willatkins** [googleads/googleads-php-lib#94] opened 2015-09-07 11:58 UTC
A couple of months ago I started intermittently having an issue described below after months of no issues successfully using the api and php client library.

We have a scheduled job that runs early in the morning (around 4:30 am UK time) and downloads a large campaign report.

Intermittently it will fail, e.g. it worked for two days, then failed on the third (with no changes on our side).

The error returned is "An error has occurred: Unknown SSL protocol error in connection to accounts.google.com:443", it then returns no results.  If I run the same job during the day it always seems to work, but this could be coincidence.

I followed a stackoverflow link (http://stackoverflow.com/questions/3234140/curl-error-35-unknown-ssl-protocol-error-in-connection) which was recommended on https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/lLF6omtcrak/cjEDtdoYBgAJ, but wasn't entirely sure how to troubleshoot the issue with the information there? I tried adding curl_setopt($ch, CURLOPT_SSLVERSION, 3); // Force SSLv3 to fix Unknown SSL Protocol error, to the report utils file in the client libraries, but the issue persisted.

Environment:
OS: Windows Server
PHP Client Library: 6.2.0
API Version: v201506

Any ideas on what could be causing the issues, or under what circumstances that error would appear? Could it be something to do with the time of day the job is running? Any ideas on how to troubleshoot, or perhaps a way to get the client libraries to retry if the above error happens?

Let me know what other information would be useful.

Thanks,
Will

**Comment by vtsao** [comment] 2015-09-08 14:53
FYI @fiboknacky 

This is for AdWords right? For help with diagnosing issues, we prefer if you post on the AdWords API forums:
https://groups.google.com/forum/#!forum/adwords-api

if it turns out there is a bug with the PHP client library, then please file it here.

Thanks!

**Comment by vtsao** [comment] 2015-09-08 15:58
It seems that you were rerouted here already from the API forums, so we'll try to help you diagnose this issue here.

**Comment by fiboknacky** [comment] 2015-09-09 13:15
@willatkins Let us investigate this issue further.
So far I've been informed of this issue so this may take some time for resolving.

As you said it's intermittently occurring, the causes of this issue may result from various factors, such as connections between your application and Google servers, the network settings on your side or the network settings on Google side or both.

As the first step, could you please collect some logs for me so I can escalate them?
I'm not familiar much with Windows-related networking, but it would help if you could capture some network traffics (e.g., results from [tcpdump](http://www.thegeekstuff.com/2010/08/tcpdump-command-examples/) in Linux)
In addition, if you see some patterns when the errors fail, such as a specific time of day as you mentioned, it would make investigation scope narrower and may get answers more quickly.

Thanks.
Knack

**Comment by willatkins** [comment] 2015-09-18 09:06
Hi Knack,

As it's intermittent and only seems to be an issue early in the morning
it's a little tricky to start a network trace without getting up really
early, as it takes up quite a bit of space if you run it for a long time.

What I've ended up doing is setting up a retry, so that if it fails I wait
30 seconds and try again, which is working well so far.

 //retry code
   $response = false;
   $max_retries = 5;
   $retry_count = 0;

   while(!$response && $retry_count < $max_retries) {
    try {
    $response = ReportUtils::DownloadReportWithAwql($reportQuery, NULL,
$user, $reportFormat , $options);
    } catch (Exception $e) {
  logIt("Exception, so try again" . $retry_count . " : " . $e->getMessage()
. " \n");
    printf("\n".date('m/d/Y h:i:s a', time()) .": Exception, so try again"
. $retry_count . " : %s \n", $e->getMessage());
    sleep(30);
    $retry_count ++;
    }
   }
   if($retry_count == $max_retries)
   {
logIt("Could not connect to adwords after 5 attempts\n");
    throw new Exception('Could not connect to adwords after 5 attempts');
   }


In the logs I received, it did fail once, but on the second try went
through correctly.

09/18/2015 04:32:41 am: Exception, so try again0 : Unknown SSL protocol
error in connection to accounts.google.com:443

If I have some more time, I'll try to replicate and grab a network trace,
but as mentioned it's intermittent and doesn't break when I want it to!

Thanks,
Will

**Comment by vtsao** [comment] 2016-01-04 19:27
Hi Will is this issue still occurring?

**Comment by alancoleman** [comment] 2016-01-11 09:19
This looks familiar as I had a similar issue a when I started using this API a few years ago, it too was also an intermittent issue It turned out to be a lack of IPV6 support on our host.

Checkout a conversation I had with Danial Klimkin:

https://groups.google.com/forum/#!searchin/adwords-api/ipv6/adwords-api/6o6fKbvluNw/ZoJon0Xr86EJ

It may be worth trying a small edit to the MakeRequest function in the SimpleOAuth2Handler.php file: https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/Common/Util/SimpleOAuth2Handler.php

```
    protected function MakeRequest($url, $params) {
    $ch = $this->curlUtils->CreateSession($url);
    $this->curlUtils->SetOpt($ch, CURLOPT_POSTFIELDS, $params);
    
    // Added by Alan Coleman 13th July 2014
    if (defined('CURLOPT_IPRESOLVE') && defined('CURL_IPRESOLVE_V4')) {
    	$this->curlUtils->SetOpt($ch, CURLOPT_VERBOSE, TRUE);
    	$this->curlUtils->SetOpt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
    } else {
    	//$hostInfo = parse_url($this->server);
    	$hostInfo = parse_url('https://accounts.google.com');
    	if (!empty($hostInfo['host'])) {
    		$this->curlUtils->SetOpt($ch, CURLOPT_URL, str_replace($hostInfo['host'], '74.125.143.84', $url));
    		$this->curlUtils->SetOpt($ch, CURLOPT_HTTPHEADER, array('Host: ' . $hostInfo['host']));
    	}
    }
    
    $response = $this->curlUtils->Exec($ch);
    $error = $this->curlUtils->Error($ch);
    $httpCode = $this->curlUtils->GetInfo($ch, CURLINFO_HTTP_CODE);
    $this->curlUtils->Close($ch);

    if (!empty($error)) {
      throw new OAuth2Exception($error, $httpCode);
    }
    if ($httpCode != 200) {
      throw new OAuth2Exception($response, $httpCode);
    }
    return json_decode($response, true);
  }
```

**Comment by fiboknacky** [comment] 2016-01-12 09:25
Thanks Alan for sharing us your workaround.

**Comment by willatkins** [comment] 2016-01-12 09:46
Thanks Alan!

I'll check it out.

Will

**Comment by chiragvels** [comment] 2016-01-12 10:03
Hello All,

For IPV6 issue, instead doing change in individual UTIL files, I would have solution by adding the line
  
$this->SetOpt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

under CurlUtils.php located at Google/Api/Ads/Common/Util/.

I have faced this issue only to get refreshtoken using oauth.

Thanks,

**Comment by fiboknacky** [comment] 2016-02-24 07:15
@willatkins 
Have you still faced with this issue recently?

**Closed** 2016-03-08 21:08 UTC
