### ISSUE TITLE
Xml Deserializer Issue

### ISSUE THREAD

**Issue by PT-BBalazs** [googleads/googleads-php-lib#147] opened 2016-07-07 12:22 UTC
We have just migrated to BatchJobService for our positive and negative keyword upload operations, and we have been experiencing the following error ever since:

**Fatal error: Call to a member function setAccessible() on a non-object in /[...]/googleads-php-lib-master/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php on line 134**

The issue seems to be recurring; some jobs are executed fine, but more often than not we get the error above. It seems that a portion of the job is still carried out (some of the keywords are indeed uploaded), but we can't trace the error back to anything that would be related to the data we provide the API.

Based on this, and an issue that appears to be somewhat similar ( Issue #123 ) we believe this might be an API error. Could you please confirm this, or point us in the right direction to look? Thanks in advance.

**Comment by vtsao** [comment] 2016-07-07 12:25
Knack PTAL.

**Comment by fiboknacky** [comment] 2016-07-07 13:09
Hello,

If possible, could you capture the stack trace the next time you're faced with this issue?
I'm considering changing the code to be more robust.

For now, the only possible case I can think of is that you're getting an object whose `_parameterMap` isn't in it nor in its parent, but in its child objects.
That case seems not likely to happen in AdWords API, as such information (e.g., [ApiError.Type](https://developers.google.com/adwords/api/docs/reference/v201605/AdGroupCriterionService.ApiError#apierrortype), which is translated into a member in [`_parameterMap`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/v201605/AdGroupCriterionService.php#L319) in this lib) is usually provided at the top of the hierarchy. 
Other classes extending the top class will inherit this property.

Best,
Knack

**Comment by PT-BBalazs** [comment] 2016-07-12 08:32
Hello,

Just to keep you informed, we have modified our code to build a stack trace and have tried to reproduce the issue. Unfortunately it seems that we did not manage to reproduce the bug so far, but will continue in the upcoming days and weeks to do so.

Which is actually strikingly odd considering that we had this issue over 3 times the day before we posted the issue. I will keep you informed.

**Comment by fiboknacky** [comment] 2016-07-12 08:33
Hello,

Thanks so much for informing us.
If you have more updates, feel free to post here.

Best,
Knack

**Comment by vtsao** [comment] 2016-07-22 16:49
Closing for now.

**Comment by PT-BBalazs** [comment] 2016-11-03 08:42
Our e-mail communication was closed with the following:

_Per personal communication, the issue seems to be affected by the old version of XmlDeserializer from v10.0.0.
This has been fixed in v12.0.0, so upgrading to this version should fix this._

Now issue #158, which was fixed in v12.0.0, deals with one-element jobs. We were also trying to investigate how this issue was related to special characters like the ampersand. Now the thing is: we have upgraded the client library to the very latest v13.1.0, but are still getting this error, only this time on line 140 due to the changes in XmlDeserializer.

This is definately not a one-entry job and also does not appear to contain any special characters which might hinder the upload. I would be extremely grateful if you could take a look and point us in the right direction.
You see the thing is, the job seems to finish successfully, but the very response we get from the server fails to make it through deserializing, so we can't really use that to determine what is functional or not.
While checking the data we upload I can't seem to find the culprit.

**Fatal error: Call to a member function setAccessible() on a non-object in /var/userdata/web/[...]/googleads-php-lib-master/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php on line 140**

The related BatchJobId is 397086621
and the related UploadURL is https://batch-job-upload-prod-ebe9b43.storage.googleapis.com/136683444/397086621.operations.xml?GoogleAccessId=926043054183-rbu1gkdushnqrfcf47gser4u8qse2ig4@developer.gserviceaccount.com&Expires=1478765113&Signature=XUF7gr2ejgH%2FAkjmuLTIp8%2FL5GF48zZrv4LA%2Bc%2FHkJKuTWKDeSrNu5u4MJd9x5CaKrmcMERrXt0DPaEbde5s1TaWq0L7I7A54bqsqlNKTGv46wRhRxI29nfh35W2CWSU%2FKjjWwRb1Z2l5SExplj44cq%2FQXWy%2FZ%2FlXvORB3hNSRlgr19SSSx2%2Bk9N5EvQJx91zX42vouXxwFPROMkNEH%2BCRfHqhJQxrf9WGuLl1C5e%2BcdrjskB9a0TsVzv7rXSfSf6zfJ%2FddpoN75IIU5tBrT1Tk1g7MBu19AS9vBWayW6GDhpn1OTBkx17eGUDU%2BiIfuhY1TTPyDXrjNlspneJbE%2FQ%3D%3D

Soap XML log is attached.
[soap_xml.txt](https://github.com/googleads/googleads-php-lib/files/568439/soap_xml.txt)

Uploaded data is attached.
[161103_Upload_Data.xlsx](https://github.com/googleads/googleads-php-lib/files/568465/161103_Upload_Data.xlsx)

I hope the data provided is enough to get you started. Please do get back to us on the details, as this issue is becoming vastly more frustrating over time.

**Comment by fiboknacky** [comment] 2016-11-03 15:10
Hi Balazs, 

I've tried your result from batch processing with `XmlDeserializer` but still can get through it _without any problems_. The deserializer did work for all many tens of operations passed back from the server.
Thus, it looks to me that there would be some issues on your side.

Could you please provide more information, e.g., code snippet you used to get the result and deserialize it?
If possible, could you debug to get sample values of variables during the code line [131](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php#L131) - [140](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php#L140), e.g., `$elementClass`, `$iteratorClass`?

Thanks.
Knack

**Comment by PT-BBalazs** [comment] 2016-11-04 16:09
Hi knack,
We've been making the modifications you requested, and have logged the output of the $elementClass and $iteratorClass variables. We still need to clean things up though, because in the current (rather simplistic) way we output these variables right now, there isn't much to see.

Here is another (unfortunately pretty large) example, though:
BatchJob with ID 397811549
upload URL https://batch-job-upload-prod-ebe9b43.storage.googleapis.com/103337117/397811549.operations.xml?GoogleAccessId=926043054183-rbu1gkdushnqrfcf47gser4u8qse2ig4@developer.gserviceaccount.com&Expires=1478879761&Signature=RssRtNpE5UQH9h0%2BsgwyItnOqN%2FmplWkBPbvKDN2YRnzPd%2BPZBRqfjkat2a1pchB63wuhLNVTgS6z%2BypAUzXwgjxPCeeB0468yvgEWoKD3CwqnvfSSqPLKTMe7nO82lQGkMgtVYfrIUgWXkwNo2I8G9G4tX3WwmXzqKbmGUmPaKSVsyZHELtWwA0XhKEwCjucd287TrUrgiNROnLUAQ%2BFUTtUFfIyqBcnbMlWCDfBF9kJatyd3Udn4Dmvmjn%2F5705cPgAL5aSdyiSTQIkD%2FZosHJLAv2N%2FNqgXrHqcm96lV7hK7uix3f4YLKNAN%2FkxBSAkupU4XemdXebO%2FSeNkHxA%3D%3D
Soap XML log attached.
[soap_xml.txt](https://github.com/googleads/googleads-php-lib/files/571994/soap_xml.txt)

The code snippet you requested:
[addkeywords (2).php.txt](https://github.com/googleads/googleads-php-lib/files/571998/addkeywords.2.php.txt)

As for sample values of variables $elementClass and $iteratorClass, as I said we need to have things cleared up, but we get the following outputs:

```
Notice:  Undefined variable: iteratorClass in /var/userdata/web/optiguppi.com/website/www/wp-content/plugins/guppi/googleads-php-lib-master/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php on line 148

NULL

bool(false)

object(ReflectionClass)#4251 (1) {
  ["name"]=>
  string(22) "ManualCpcBiddingScheme"
}
```
Please note that these are just examples in no particular order. The very LAST entry however, is this:
```
object(ReflectionClass)#4292 (1) {
  ["name"]=>
  string(14) "CriterionError"
}
```

This is the only occurence of CriterionError in the output.

Well, I hope that was slightly helpful, but I will be getting back to you with more, hopefully better structured information as I get my hands on them.

Thanks,
Balazs

**Comment by fiboknacky** [comment] 2016-11-04 16:17
Hi Balazs,

I'm not quite sure about `ManualCpcBiddingScheme` but for `CriterionError`, one of the most mistakes so far, occurs when a user do `require_once` of all our classes.
Sometimes, `ApiError`, which is the parent class of [CriterionError](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/v201609/CampaignCriterionService.php#L683), got hidden by another [ApiError](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Util/v201609/ReportClasses.php#L37), which is the class of reporting, and consequently `XmlDeserializer` cannot work properly.
This is because in the main branch of our lib, there is no support for namespacing yet.

Could you please confirm if this is not the case?

Best,
Knack

**Comment by PT-BBalazs** [comment] 2016-11-09 09:49
Hi Knack,

This is all we have:
include_once DIR.'init.php';
require_once ADWORDS_UTIL_VERSION_PATH . '/ReportUtils.php';
require_once ADWORDS_UTIL_PATH . '/XmlDeserializer.php';
require_once ADWORDS_UTIL_VERSION_PATH . '/BatchJobUtils.php';
require_once UTIL_PATH . '/ChoiceUtils.php';
require_once UTIL_PATH . '/OgnlUtils.php'

init.php is the unmodified, "factory" version.


We have had another occurence of this error. This time, I did not record all the information, but the last entry in the dump directly before the fatal error was:

```
object(ReflectionClass)#3212 (1) {
  ["name"]=>
  string(21) "AdGroupCriterionError"
}
```

Which is only slightly different to the previous CriterionError.

I have no idea as to what could possibly be the issue.

**Comment by fiboknacky** [comment] 2016-11-09 11:32
Hi Balazs,

First,

> require_once ADWORDS_UTIL_VERSION_PATH . '/ReportUtils.php';
> require_once ADWORDS_UTIL_PATH . '/XmlDeserializer.php';

This is the cause.

As explained in the previous reply, when you do `require_once` for ReportUtils as well, it will in turn require reporting `ApiError`, which is different from that of SOAP services' `ApiError`.
The reporting `ApiError` doesn't have a `_paramaterMap` variable. That's why all classes extending `ApiError`, e.g., `CriterionError`, `AdGroupCriterionError` will fail.

Could you please try not requiring `ReportUtils.php` and see what happened?
I'm quite sure that this will resolve your issue.
Please see #127 for more information.

Best,
Knack

**Comment by PT-BBalazs** [comment] 2016-11-09 13:40
Hi Knack,

I was just in the middle of building an upload list when this happened. To better understand, the workflow process of our application is the following:
- We request keyword data from Google using
- We work on that data
- We upload the modified keywords

I was just busy doing work in Phase 2 when we got your answer. We quickly modified the require_once files, and it looks like everything fine. (Please note that as we don't get the Fatal error all the time this will require further testing, but it's a good start).

However, if we do not require_once ReportUtils.php we can not run our request for keyword data (Phase 1), as ReportUtils is missing. We used the original DownloadCriteriaReportWithAwql sample to build that request.

So we have a situation that we do need ReportUtils, but it seems we can't require it to avoid this error.

I think we now fully understand the problem, but unfortunately we did not see this coming. We have the entire application programmed in one nice package, but as we understand, to avoid the problem we would need to split it into two completely independent parts, one requiring ReportUtils and the other one requiring XmlDeserializer. This is the same issue as in #127 

So in the end we will try to including ReportUtils only within the function we need it, but this is somewhat... well, you understand. Absolutely looking forward to the namespacing feature, then.


We will make the appropriate modifications and do some heavy testing on this. It might take a while though - I will keep you updated on the results.

**Comment by fiboknacky** [comment] 2016-11-09 14:00
Hi Balazs,

Thanks for detailed situation.
I know that this is tough for you. Sorry for this convenience.
What you're saying to use as a workaround looks good.

I'll close this issue for now. If you find any issues related to this, feel free to open it again.
If you find other issues, please create a new one.

Thanks!
Knack

**Closed by fiboknacky** 2016-11-09 14:00 UTC
Labels: bug
