### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable

### ISSUE THREAD

**Issue by steponafish** [googleads/googleads-php-lib#489] opened 2018-05-11 19:30 UTC
Hello. 
I found a thread on Google Groups to use this repository for this issue. In that thread it was said that the PHP library requires 5.5.9 or higher. I'm currently running on 7.0.29 and I'm still getting this error. 

I'm getting this error: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/........./wp-content/themes/clientTheme/adwords/symfony/serializer/Normalizer/AbstractObjectNormalizer.php on line 238

I got this error when testing out the DownloadCriteriaReportWithAwql.php file.
I took a look at line 238 in the AbstractObjectNormalizer file just to see and it's a line that's been commented out. 

Any help or advice?

**Comment by fiboknacky** [comment] 2018-05-12 04:39
Could you tell what is the version of Symfony serializer you have installed?

**Comment by steponafish** [comment] 2018-05-13 15:38
The Changelog in the Symfony directory says 4.0.0

**Comment by fiboknacky** [comment] 2018-05-14 01:23
OK. Symfony Serializer v4.0.0 needs PHP v7.1.3. 
This is probably the cause why you see an error because there might be some syntax that your PHP version doesn't recognize.

**Comment by steponafish** [comment] 2018-05-14 01:25
So what do I do? I cannot increase my php version.

**Comment by fiboknacky** [comment] 2018-05-14 04:39
How did you install Symfony serializer? Is it installed via other libraries by composer? 
I can't see your project directory structure so I can't advice more.
Could you explain in detail what libraries do you use and what does your composer.json look like?

**Comment by steponafish** [comment] 2018-05-14 14:58
I downloaded the entire adwords api via composer. I did this two weeks ago.

composer require googleads/googleads-php-lib

**Comment by fiboknacky** [comment] 2018-05-14 15:11
Could you please answer all my previous questions in the previous reply?
This will save us turn-around time and it would lead us to the solution more quickly. 
The more details you could provide, the faster I can understand your circumstances.
Thanks. :)

**Comment by steponafish** [comment] 2018-05-14 15:19
**How did you install Symfony serializer? and Is it installed via other libraries by composer?**
I installed Symfony and the the rest of the googleads-php files via Composer and then I moved them to my webhost environment via FTP. I cannot install it otherwise onto my webhost.

**Could you explain in detail what libraries do you use and what does your composer.json look like?**
I'm not sure what libraries I use because I haven't finished the project. This project will be a custom dashboard for clients to see their own data. Right now I'm trying to use one of the reporting sample DownloadCriteriaReportWithAwql to view an XML or CSV string and it's throwing me the error above.

Attached is a screenshot of the composer.json found in the Symfony directory.
![screen shot 2018-05-14 at 9 16 41 am](https://user-images.githubusercontent.com/8648576/40006419-99368508-5757-11e8-9c44-03ed14f61e07.png)

**Comment by fiboknacky** [comment] 2018-05-14 15:36
Thanks for the information.
I meant _your project_'s composer.json, not the Serializer's composer.json.
Could you share that too?

**Comment by steponafish** [comment] 2018-05-14 15:40
Here's the project's composer.json. I have not changed anything in this file since downloading via composer.
![screen shot 2018-05-14 at 9 39 26 am](https://user-images.githubusercontent.com/8648576/40007690-b9187608-575a-11e8-947b-f02195113d50.png)

**Comment by fiboknacky** [comment] 2018-05-14 15:44
Hmm.. Everything should be alright. 
Can you try, _in your local machine_, removing the `vendor/` directory, run `composer install`, and try again?

**Comment by steponafish** [comment] 2018-05-14 15:46
Just to let you know, these files are from my web host. So do I need to redo everything?

**Comment by fiboknacky** [comment] 2018-05-14 15:51
At least, you would need to try in the local machine first. 
I wonder why composer install a dependency that is not compatible with your PHP version.

If you have developed something in your project file, you can try on a clean directory first.
By the way, you would need to use the same PHP version (7.0) as your web host too.

**Comment by steponafish** [comment] 2018-05-14 15:52
I just redownloaded the vendor files. How do I check to see if they are for PHP 7.0?

**Comment by fiboknacky** [comment] 2018-05-14 16:00
Just run what you originally ran to get the error message, probably DownloadCriteriaReportWithAwql?

**Comment by steponafish** [comment] 2018-05-14 16:08
I was able to successfully run it on my local machine. I'm going to upload all the files to my webhost and test it there.

**Comment by fiboknacky** [comment] 2018-05-15 03:31
So, there's no other way. If you need to install via local machine and copy files over to the host, you need to find a machine that have the same PHP version as your web host.
Alternatively, you could install Symfony serializer by yourself by doing the following:
* Remove only `symfony/serializer` in your `vendor/`
* Run `composer require symfony/serializer:3.1`

Then copy newly created `symfony/serializer` over to the `vendor/` directory in your web host.

**Comment by steponafish** [comment] 2018-05-15 15:57
Is that serializer version compatible to php v7.0?

**Comment by fiboknacky** [comment] 2018-05-15 16:00
You can check by yourself by seeing `require` of `composer.json` of any projects.

**Comment by steponafish** [comment] 2018-05-15 17:47
It says "symfony/serializer": "^2.8.0 || ^3.0.3 || ^4.0.0"

**Comment by fiboknacky** [comment] 2018-05-15 17:51
> It says "symfony/serializer": "^2.8.0 || ^3.0.3 || ^4.0.0"

That's this library's composer.json and what you checked is a version of serializer, not PHP.
You need to check composer.json of symfony/serializer, not this library.
Look for the entry of `php`.

By the way, I highly recommend you to read through [this composer guide](https://getcomposer.org/doc/01-basic-usage.md).
It looks like you've not fully understood things in composer yet.

I'm going to close this issue for now, as the root cause has been found and I provided a solution.
Feel free to ask more questions if you still have ones.

**Closed by fiboknacky** 2018-05-15 17:51 UTC
Labels: P2

**Comment by mrpavlikov** [comment] 2020-01-16 15:15
```bash
mrpavlikov@smetana:/var/www/data-importer$ composer require googleads/googleads-php-lib --ignore-platform-reqs
Using version ^44.0 for googleads/googleads-php-lib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for googleads/googleads-php-lib ^44.0 -> satisfiable by googleads/googleads-php-lib[44.0.0].
    - googleads/googleads-php-lib 44.0.0 requires symfony/serializer ^2.8.0 || ^3.0.3 || ^4.0.0 -> no matching package found.```

Symfony 5 has 5.0.2 version of symfony/serializer atm, so I am unable to install this package. Is there any change to fix that?

**Comment by mrpavlikov** [comment] 2020-01-16 15:16
nvm me, I see https://github.com/googleads/googleads-php-lib/issues/637
