### ISSUE TITLE
[PHP8.1] PHP Deprecated: Return type of Google\AdsApi\Common\AdsSoapClient::__doRequest

### ISSUE THREAD

**Issue by mrceperka** [googleads/googleads-php-lib#742] opened 2022-03-22 13:39 UTC
Hello,

I've recently came across this error:

```txt
PHP Deprecated:
Return type of Google\AdsApi\Common\AdsSoapClient::__doRequest($request, $location, $action, $version, $one_way = 0)
should either be compatible with
SoapClient::__doRequest(string $request, string $location, string $action, int $version, bool $oneWay = false): ?string,
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

Could this be fixed in a future version? Or can I fix this on my end somehow?

Thanks.

**Comment by PierrickVoulet** [comment] 2022-05-05 18:57
Hi @mrceperka - This seems to be a duplicate of #733, could you confirm?

**Comment by mrceperka** [comment] 2022-05-09 13:33
@PierrickVoulet yes, looks like it.

**Closed as completed** 2022-05-09 14:00 UTC
Labels: bug
